State-of-Rhode-Island-eCMS/ecms_profile

.gitignore, CHANGELOG.md, composer.json, ecms_base/config/install/content_moderation_notifications.content_moderation_notification.ready_for_review.yml, ecms_base/ecms_base.info.yml, phpcs.xml, tests/src/Functional/AllProfileInstallationTestsAbstract.php
Require the content moderation notifications module, and include the default notification config in the install.
=> Content moderation notifications

CHANGELOG.md, ecms_base/features/custom/ecms_speeches/config/install/core.base_field_override.node.speech.promote.yml, ecms_base/features/custom/ecms_speeches/config/install/core.entity_form_display.node.speech.default.yml, ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.default.yml, ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.teaser.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_date.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_long_title.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_text.yml, ecms_base/features/custom/ecms_speeches/config/install/field.storage.node.field_speech_date.yml, ecms_base/features/custom/ecms_speeches/config/install/field.storage.node.field_speech_long_title.yml, ecms_base/features/custom/ecms_speeches/config/install/field.storage.node.field_speech_text.yml, ecms_base/features/custom/ecms_speeches/config/install/node.type.speech.yml, ecms_base/features/custom/ecms_speeches/ecms_speeches.features.yml, ecms_base/features/custom/ecms_speeches/ecms_speeches.info.yml, ecms_base/features/custom/ecms_speeches/tests/src/Functional/EcmsSpeechesInstallTest.php
Adds the speech content type via features
https://thinkoomph.jira.com/browse/RIG-47
=> Add optional speech content type as feature

composer.json
Latest release seems to work fine.
| `CHANGELOG` reflects changes? | no
https://thinkoomph.jira.com/browse/RIG-75
=> Update webform to alpha19

ecms_base/config/install/block.block.tabs.yml, ecms_base/modules/custom/ecms_layout/layouts/layout--four-column.html.twig, ecms_base/modules/custom/ecms_layout/layouts/layout--one-column.html.twig, ecms_base/modules/custom/ecms_layout/layouts/layout--three-column.html.twig, ecms_base/modules/custom/ecms_layout/layouts/layout--two-column.html.twig, ecms_base/modules/custom/ecms_layout/src/EcmsLayout.php, ecms_base/modules/custom/ecms_layout/src/Plugin/Layout/FourColumnLayout.php, ecms_base/modules/custom/ecms_layout/src/Plugin/Layout/LayoutBase.php, ecms_base/modules/custom/ecms_layout/src/Plugin/Layout/ThreeColumnLayout.php, ecms_base/themes/custom/ecms/ecms.libraries.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/layout/layout--four-column.html.twig, ecms_base/themes/custom/ecms/templates/layout/layout--one-column.html.twig, ecms_base/themes/custom/ecms/templates/layout/layout--three-column.html.twig, ecms_base/themes/custom/ecms/templates/layout/layout--two-column.html.twig, ecms_base/themes/custom/ecms/templates/layout/page--landing-page.html.twig
This PR connects the existing layout templates to their pattern lab counterparts. Some changes to the templates were made to keep them in sync. Also included are some minor changes throughout ecms_layout and ecms theme.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-68
=> Configure layout options

ecms_base/modules/custom/ecms_workflow/tests/src/ExistingSite/InstallationTest.php
Writes a test that ensures new content types are assigned to the workflow by checking for new permissions.
=> Update workflow test to include new content type

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/features/custom/ecms_executive_orders/tests/src/ExistingSite/EcmsExecutiveOrdersInstallTest.php, ecms_base/features/custom/ecms_hotel/tests/src/ExistingSite/EcmsHotelInstallTest.php, ecms_base/features/custom/ecms_projects/tests/src/ExistingSite/EcmsProjectsInstallTest.php, ecms_base/features/custom/ecms_publications/tests/src/ExistingSite/EcmsPublicationsInstallTest.php, ecms_base/features/custom/ecms_speeches/tests/src/ExistingSite/EcmsSpeechesInstallTest.php
Installs the contrib module moderated_content_bulk_publish
This allows for bulk "publish/unpublish" content from the main content admin view.
There is a D9 core issue linked from the module that should eventually eliminate the need for this module.
https://thinkoomph.jira.com/browse/RIG-22 …
=> Add the moderated_content_bulk_publish module

CHANGELOG.md
This is the initial release of the profile and can be considered fully in beta now.
| Did you perform browser testing? | n/a
=> Prepare the changelog for the 0.1.0 release.

CHANGELOG.md
Prepare the for deployment of 0.1.1
| Relevant links | [rig-6](https://thinkoomph.jira.com/browse/rig-6)
=> Prepare changelog for the 0.1.1 release

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.info.yml, ecms_base/themes/custom/ecms/ecms.libraries.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/node.html.twig, ecms_base/themes/custom/ecms/templates/layout/html.html.twig, ecms_base/themes/custom/ecms/templates/layout/page.html.twig, ecms_base/themes/custom/ecms/templates/layout/region.html.twig, ecms_base/themes/custom/ecms/theme-settings.php
This PR includes setting up some of the main Twig templates and hooking them up with Pattern Lab. Also included is some minor changes to theme settings form.
=> Base templates and theme settings updates

CHANGELOG.md, ecms_base/themes/custom/ecms/config/optional/block.block.mainnavigation.yml, ecms_base/themes/custom/ecms/ecms.info.yml, ecms_base/themes/custom/ecms/ecms.libraries.yml, ecms_base/themes/custom/ecms/templates/layout/page--landing-page.html.twig, ecms_base/themes/custom/ecms/templates/navigation/menu.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--accordion-builder.html.twig
This PR supports the work done in https://github.com/State-of-Rhode-Island-eCMS/ecms_patternlab/pull/12/files.
- Page tpls have been updated to use classy and feature a class to toggle full-width.
- The accordion paragraph was connected with PL.
- The main menu was connected with PL and had a default block placed.
- The JS for pattern-lab was imported
| Relevant links | https://thinkoomph.jira.com/browse/RIG-37
=> Page template updates and Accordion, Header, Menu theming

CHANGELOG.md, composer.json
This fixes the tabledrag bug in Claro
| Relevant links | https://www.drupal.org/project/drupal/issues/3083051
=> Patch for claro theme tabledrag

CHANGELOG.md, composer.json, ecms_base/config/install/extlink.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.profile
This adds the external links module as a profile dependency and adds a new hook_update_n function to install the module on existing sites.
| Relevant links | [RIG-124](https://thinkoomph.jira.com/browse/rig-124)
=> Add and configure the external links module

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.profile, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.icon_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.icon_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_icon.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_list_title.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_icon.yml, ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.icon_card.yml, ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.info.yml
Adds a new paragraph type to the existing paragraphs feature. Adds SVG Image module as a default dependency to the profile.
Adds update hook that will install the svg image module to existing sites.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-69
=> Install SVG Image and add Icon Card paragraph type

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.media_item_image.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.media_item_image.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.media_item_image.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.media_item_video.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.media_item_video.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.icon_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.media_item.default.yml, ecms_base/themes/custom/ecms/config/optional/block.block.mainnavigation_2.yml, ecms_base/themes/custom/ecms/config/optional/block.block.tabs.yml, ecms_base/themes/custom/ecms/ecms.info.yml, ecms_base/themes/custom/ecms/templates/fields/field--field-icon.html.twig, ecms_base/themes/custom/ecms/templates/navigation/menu--minor.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-card.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--media-item.html.twig
This PR connects the work done in Pattern Lab PR: https://github.com/State-of-Rhode-Island-eCMS/ecms_patternlab/pull/14
Changes include:
- Add menu_block module and re-add the navigation blocks to use the new config
- Add Sidebar navigation PL connector
- Define new regions for ecms_base
- Add Icon Card PL connector
- Add Media Item PL connector
| Relevant links | https://thinkoomph.jira.com/browse/RIG-69
=> Theme build out ( Sidebar Nav, Media Item, Icon Card )

CHANGELOG.md
Prepare the changelog for the 0.1.3 release.
=> Prepare the changelog for 0.1.3 release

CHANGELOG.md, composer.json, ecms_base/ecms_base.profile
Remove patch from webform_encrypt it's not working correctly and causes submissions to not be legible in the admin.
Adds update hook to ensure encryption modules are enabled and config in place.
Also ensures pathauto  and redirect modules are enabled with config in place (not sure why this didn't happen with last update hook, may be Acquia environment error). …
=> Webform encryption updates

CHANGELOG.md
Get ready for 0.1.4.
| Relevant links | [rig-6](https://thinkoomph.jira.com/browse/rig-6)
=> Prepare changelog for the 0.1.4 release

CHANGELOG.md
Prepare for the 0.1.5 release.
| Relevant links | [RIG-6](https://thinkoomph.jira.com/browse0rig-6)
=> Prepare changelog for 0.1.5 release

CHANGELOG.md, composer.json, docs/theming.md, ecms_base/features/custom/ecms_executive_orders/tests/src/ExistingSite/EcmsExecutiveOrdersInstallTest.php, ecms_base/features/custom/ecms_hotel/tests/src/ExistingSite/EcmsHotelInstallTest.php, ecms_base/features/custom/ecms_projects/tests/src/ExistingSite/EcmsProjectsInstallTest.php, ecms_base/features/custom/ecms_speeches/tests/src/ExistingSite/EcmsSpeechesInstallTest.php
=> Rig 138/theme debug

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/theme-settings.php
Resolve invalid json theme setting file. Update translate functions with file media
| Did you apply meaningful labels to the pull request? | yes/
| Relevant links | https://thinkoomph.jira.com/browse/RIG-130
=> Resolve invalid json theme setting file. Update translate functions with file media

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.column_container.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.media_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.column_container.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.media_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.column_container.field_components.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.media_item.field_link.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_components.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_link.yml, ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.column_container.yml, ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.info.yml, ecms_base/themes/custom/ecms/templates/content/node--promotions--teaser.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--accordion-builder.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--column-container.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--file-list.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-card.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--media-item.html.twig
This PR includes two separate changes to eCMS paragraphs. It adds a column container paragraph which allows other paragraphs to be referenced. It also adds linking to media items.
=> Add column container paragraph and link media items

CHANGELOG.md
Prepare the changelog for the 0.1.7 tag.
=> Prepare changelog for 0.1.7 release

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/core.base_field_override.paragraph.media_item.created.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.base_field_override.paragraph.media_item.status.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.media_item.field_caption.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.media_item.field_link.yml, ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.paragraph.media_item.yml, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--media-item.html.twig
This adds conditional logic for an empty link. 
Enables translation for the media item paragraph, specifically the caption and link fields.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-69
=> Update media item for translation

CHANGELOG.md, ecms_base/features/custom/ecms_promotions/config/install/core.entity_view_display.node.promotions.teaser.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/blocks/block--menu-block--minor.html.twig, ecms_base/themes/custom/ecms/templates/content/node--promotions--teaser.html.twig
This is a small PR that preprocesses the sidebar nav and connects promo teasers to PL.
=> Sidebar nav preprocess and connect promotions teaser to PL

CHANGELOG.md
=> Prepare CHANGELOG for release 0.1.8

CHANGELOG.md, composer.json, ecms_base/config/install/scheduled_transitions.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.profile, ecms_base/features/custom/ecms_basic_page/ecms_basic_page.info.yml, ecms_base/features/custom/ecms_event/ecms_event.info.yml, ecms_base/features/custom/ecms_executive_orders/ecms_executive_orders.info.yml, ecms_base/features/custom/ecms_hotel/ecms_hotel.info.yml, ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml, ecms_base/features/custom/ecms_location/ecms_location.info.yml, ecms_base/features/custom/ecms_person/ecms_person.info.yml, ecms_base/features/custom/ecms_press_release/ecms_press_release.info.yml, ecms_base/features/custom/ecms_projects/ecms_projects.info.yml, ecms_base/features/custom/ecms_promotions/ecms_promotions.info.yml, ecms_base/features/custom/ecms_publications/ecms_publications.info.yml, ecms_base/features/custom/ecms_speeches/ecms_speeches.info.yml, ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php, ecms_base/modules/custom/ecms_workflow/tests/src/Unit/EcmsWorkflowBundleCreateTest.php
Adds the scheduled transitions module, and associated config. Needed for workflows.
Adds permissions via Ecms workflow module.
Updates config via hook 9019.
Updates unit test.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-91
=> Add scheduled transitions

CHANGELOG.md
Prepare the changelog for 0.1.9.
| Unit/Functional tests reflect changes? | yesn/a
| Did you perform browser testing? | n/a
=> Prepare changelog for 0.1.9 release

CHANGELOG.md
Prepare changelog for the 0.2.0 release.
=> Prepare changelog for 0.2.0 release.

CHANGELOG.md
=> Prepare the changelog for 0.2.1

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/content/node--notification--teaser.html.twig
Added label to notification teasers.
=> Added label to notification teasers.

CHANGELOG.md
=> Prepare CHANGELOG for release 0.2.3

CHANGELOG.md, composer.json, ecms_base/config/install/search_api.index.database.yml, ecms_base/config/install/search_api.server.database.yml, ecms_base/config/install/search_api.settings.yml, ecms_base/config/install/search_api_db.settings.yml, ecms_base/config/install/views.view.site_search.yml, ecms_base/ecms_base.info.yml
Using the search api module, this creates a database search and index, along with a view (page) for display.
This is an initial setup that will allow the theming of the search to proceed, while the search setup is finalized.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-131
=> Add database search index

CHANGELOG.md
=> Prepare changelog for 0.2.4

CHANGELOG.md, ecms_base/config/install/views.view.site_search.yml
=> Add current language fiter to search view

CHANGELOG.md
=> Prepare changelog for release 0.2.5

CHANGELOG.md
Prepare for the 0.2.6 release.
=> Prepare changelog for 0.2.6 release

CHANGELOG.md
Prepare for the 0.2.7 release tag.
=> Prepare changelog for 0.2.7 release

CHANGELOG.md
=> Prepare changelog for 0.2.8

CHANGELOG.md, ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/PromotionsGlobalBlock.php
Implement getCacheTags method for global promotions block, so it is rebuilt with any change to promotion content.
=> Add cache tags to global block

CHANGELOG.md
=> Prepare changelog for 0.2.9

ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml, ecms_base/features/custom/ecms_basic_page/config/install/field.field.node.basic_page.field_basic_page_promotions.yml, ecms_base/features/custom/ecms_event/config/install/core.entity_form_display.media.event_image.default.yml, ecms_base/features/custom/ecms_event/config/install/field.field.node.event.field_event_promotions.yml, ecms_base/features/custom/ecms_location/config/install/field.field.node.location.field_location_promotions.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.media_item_audio.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.media_item_image.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.media_item_video.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.accordion_builder.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.column_container.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.file_list.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.formatted_text.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.icon_card.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.media_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.media_item.preview.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.text_card.preview.yml, ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.info.yml, ecms_base/features/custom/ecms_person/config/install/core.entity_form_display.media.person_headshot.default.yml, ecms_base/features/custom/ecms_person/config/install/field.field.node.person.field_person_promotions.yml, ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_promotions.yml, ecms_base/features/custom/ecms_promotions/config/install/core.entity_form_display.media.promotional_image.default.yml
Moves "promotions" field below page components for basic page form display.
Adds preview display modes for all paragraph types, and sets the basic page form display settings to use that display.
Removes the "Path" field from the form display of the following Media types:
- file
- image
- audio
- video
- event image
- promotional image
- personal photo
No update hooks required since these are all feature based changes
| Risk …
=> Basic page and paragraph admin form display updates

CHANGELOG.md
Prepare for the 0.3.0 release.
=> Prepare changelog for the 0.3.0 release

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.preview.yml
Swap the default and preview modes.
| Documentation reflects changes? | /no
| Risk level | Low,
| Relevant links | https://thinkoomph.jira.com/browse/RIG-179
=> Fix embed paragraph display modes

CHANGELOG.md
=> Prepare changelog for 0.3.1

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme
=> Rig 6/pubs bug

CHANGELOG.md
=> Prepare changelog for release 0.3.2

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme
=> Updated language sorting

CHANGELOG.md
=> Prepare changelog for 0.3.3

.github/workflows/develop.yml, composer.json, ecms_base/config/install/system.performance.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, scripts/develop.sh
Adds memcache module to default install.
Introduces performance YML - Sets cache time to 1 hour.
Enables syslog module for default install.
Removes views_ui from default install.
Adds memcache to local lando file during develop.sh script .
Update hook 9034 to enable modules, disable views_ui.
Adds a memcache PHP extension install to the develop.yml build script.
This PR is needed as well to properly enable on ACSF: https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/pull/61
| Unit/Functional tests …
=> Memcache added and misc performance updates

CHANGELOG.md
=> Prepare changelog for release 0.3.4

CHANGELOG.md, ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.paragraph.publication_list.default.yml, ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.paragraph.publication_list.default.yml, ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_language.yml, ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_list_language.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--publication-list.html.twig
This PR adds a language filter to publication list paragraph.
| Did you perform browser testing? | /no
=> Add language filter to publication list

.github/workflows/develop.yml, CHANGELOG.md, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
Moves memcache to the install hook, as opposed to a direct dependency.
Comments out functional workflow to bypass unknown errors.
Specifies ubuntu 18.04 so that PHP version conflict during CI is avoided.
Removes memcache image and config from CI workflows.
| Did you perform browser testing? | ye
| Relevant links | RIG-171
=> Memcache updates

CHANGELOG.md
=> Prepare changelog for release 0.3.5

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig
Fix syntax error in number_format
=> Fix syntax error in number_format

CHANGELOG.md
=> Prepare CHANGELOG for 0.3.6 release

CHANGELOG.md
=> Prepare CHANGELOG for 0.3.7 release

CHANGELOG.md
=> Prepare changelog for the 0.3.8 tag.

CHANGELOG.md
=> Prepare changelog for 0.3.9 release

CHANGELOG.md, ecms_base/features/custom/ecms_basic_page/config/install/field.field.node.basic_page.field_basic_page_paragraphs.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.gallery.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.gallery_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.gallery.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.gallery_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.accordion_builder.field_item_flexible_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.gallery.field_gallery_items.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.gallery_item.field_gallery_item.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.gallery_item.field_gallery_item_caption.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_gallery_item.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_gallery_item_caption.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_gallery_items.yml, ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.gallery.yml, ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.gallery_item.yml, ecms_base/themes/custom/ecms/ecms.libraries.yml, ecms_base/themes/custom/ecms/templates/blocks/block--system-menu-block.html.twig, ecms_base/themes/custom/ecms/templates/fields/field--paragraph--field-gallery-items.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--gallery-item.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--gallery.html.twig
This PR adds gallery functionality to eCMS. Two new paragraphs have been added to support this. Gallery and Gallery item.
The tiny slider library was used to supply the basic JS functionality.
=> Add gallery functionality

CHANGELOG.md, ecms_base/modules/custom/ecms_migration/README.md
=> Updated docs

CHANGELOG.md
=> Prepare changelog for release 0.4.0

CHANGELOG.md
=> Prepare changelog for release 0.4.1

CHANGELOG.md, ecms_base/features/custom/ecms_basic_page/config/install/core.entity_view_display.node.basic_page.default.yml, ecms_base/features/custom/ecms_event/config/install/core.entity_view_display.node.event.default.yml, ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.node.landing_page.default.yml, ecms_base/features/custom/ecms_location/config/install/core.entity_view_display.node.location.default.yml, ecms_base/features/custom/ecms_notification/config/install/core.entity_view_display.node.notification.default.yml, ecms_base/features/custom/ecms_person/config/install/core.entity_view_display.node.person.default.yml, ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.default.yml, ecms_base/features/custom/ecms_promotions/config/install/core.entity_view_display.node.promotions.default.yml, ecms_base/features/custom/ecms_publications/config/install/core.entity_view_display.node.publication.default.yml
This PR resolves a search related issue where the generic links field was throwing a warning with the default search view. 
| Relevant links | https://thinkoomph.jira.com/browse/RIG-195
=> Remove links from default displays

CHANGELOG.md, composer.json, ecms_base/config/install/honeypot.settings.yml, ecms_base/config/install/webform.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
Add honeypot module and config, will be installed by default.
Add webform setting (updates webform.settings.yml). 
Includes an update hook to sync this new setting and install honeypot.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-212
=> Add honeypot module

CHANGELOG.md, ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SiteNotificationsBlock.php
| Relevant links | https://thinkoomph.jira.com/browse/RIG-225
=> Add cachetags method to notifications block

CHANGELOG.md, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page.yml, ecms_base/modules/custom/ecms_migration/src/Plugin/migrate/process/RemoveAttribute.php, ecms_base/modules/custom/ecms_migration/tests/src/Unit/process/RemoveAttributeTest.php
Adds a custom process plugin to remove a given attribute from the markup. 
Updates the basic page migration to use the filter.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-216
=> Add migration process plugin to strip HTML attributes

CHANGELOG.md
=> Prepare changelog for release 0.4.2

CHANGELOG.md, composer.json, ecms_base/config/install/filter.format.minimal.yml, ecms_base/ecms_base.install, ecms_base/features/custom/ecms_landing_page/config/install/block_content.type.header_image_action.yml, ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.content_components.default.yml, ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.header_image_action.default.yml, ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.block_content.header_image_action.default.yml, ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.node.landing_page.full.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_link.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_page_title_enabled.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_text_bg_color.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_text_position.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_image.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_hia_link.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_hia_page_title_enabled.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_hia_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_hia_text_bg_color.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_hia_text_position.yml, ecms_base/features/custom/ecms_landing_page/config/install/language.content_settings.block_content.header_image_action.yml, ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml, ecms_base/modules/custom/ecms_layout/layouts/layout--one-column.html.twig, ecms_base/modules/custom/ecms_layout/src/Plugin/Layout/LayoutBase.php, ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--header-image-action.html.twig, ecms_base/themes/custom/ecms/templates/fields/field--field-hia-text.html.twig
This PR includes the new Header, Image, and Action component as well as several small fixes/additions for Layout Builder. Those changes include:
- Add patch to fix LB UI issues in Safari and Firefox
- Resolve issue with Full-width setting default value
- Add tabs to default layout builder display
- Add block description to form display for content components
| Relevant links | https://thinkoomph.jira.com/browse/RIG-223, https://thinkoomph.jira.com/browse/RIG-202, …
=> Header, Image, and Action component. Minimal Text Format and additional fixes to Layout Builder

CHANGELOG.md
=> Prepare changelog for release 0.4.3

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/content/node--promotions--teaser.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--gallery-item.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--media-item.html.twig
Add "hasTranslation" tests to the template files.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-220
=> Fix missing translation error

CHANGELOG.md
=> Prepare changelog for release 0.4.4

CHANGELOG.md
=> Prepare CHANGELOG for 0.4.5

CHANGELOG.md
=> Prepare CHANGELOG for 0.4.6

CHANGELOG.md, ecms_base/config/install/language.content_settings.menu_link_content.menu_link_content.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.accordion_builder.field_item_flexible_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.media.media_item_video.yml, ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.paragraph.gallery.yml, ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.paragraph.gallery_item.yml
Updates translation config settings to match what's been updated on prod.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-257
=> Update translation settings to match prod

CHANGELOG.md, ecms_base/features/custom/ecms_event/config/install/core.entity_form_display.node.event.default.yml, ecms_base/features/custom/ecms_event/config/install/core.entity_view_display.node.event.default.yml, ecms_base/features/custom/ecms_event/config/install/core.entity_view_display.node.event.teaser.yml, ecms_base/features/custom/ecms_event/config/install/field.field.node.event.field_event_registration_url.yml, ecms_base/features/custom/ecms_event/config/install/field.field.node.event.field_event_virtual_meeting_url.yml, ecms_base/features/custom/ecms_event/config/install/field.storage.node.field_event_registration_url.yml, ecms_base/features/custom/ecms_event/config/install/field.storage.node.field_event_virtual_meeting_url.yml, ecms_base/features/custom/ecms_event/ecms_event.info.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/node--event--full.html.twig, ecms_base/themes/custom/ecms/templates/fields/field--node--field-event-type.html.twig
This PR themes the even full display mode. Two new fields were added for registration and virtual meeting URLs.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-188
=> Theme event full display

CHANGELOG.md, ecms_base/config/install/extlink.settings.yml, ecms_base/ecms_base.install
This PR removes top level domains for external link module.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-246
=> Remove top level domain settings for ext link

CHANGELOG.md, ecms_base/config/install/system.performance.yml, ecms_base/ecms_base.install
| Relevant links | https://thinkoomph.jira.com/browse/RIG-247
=> Update cache max lifetime

ecms_base/modules/custom/ecms_migration/README.md
| `CHANGELOG` reflects changes? | no
| Relevant links | https://thinkoomph.jira.com/browse/RIG-262
=> Update readme docs for migrations

CHANGELOG.md
=> Prepare changelog for release 0.4.7

CHANGELOG.md, ecms_base/features/custom/ecms_promotions/config/install/field.field.media.promotional_image.field_promotion_image.yml, ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/node--promotions--teaser.html.twig
Add twig logic for promotion teaser.
Update promotional image media item translation settings.
Add code to trim publication urls in migrations, and another trim in the theme file itself to be safe.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-269
=> Update promotion translations and publication migration

CHANGELOG.md
=> Prepare CHANGELOG for 0.4.8 release

CHANGELOG.md
=> Prepare CHANGELOG for 0.4.9 release

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/content/node--promotions--teaser.html.twig
This PR resolves an issue with promotion URLs
=> Resolve issue with promotion URLs

CHANGELOG.md
=> Prepare CHANGELOG for 0.5.0

CHANGELOG.md, ecms_base/config/install/content_moderation_notifications.content_moderation_notification.ready_for_review.yml, ecms_base/ecms_base.install
Added node title, revision author, and log comment to notification email when submitted for review.
| Relevant links | JIRA issue
https://thinkoomph.jira.com/browse/RIG-277?atlOrigin=eyJpIjoiMWZjMjJjZjBjYWQ1NGEzMWJiYjY4OTY4YTE0YmQwYzYiLCJwIjoiaiJ9
=> Update notification text

CHANGELOG.md, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page.yml
Updates the migration config for basic page to use basic_html.
Update hook to update the migration config on existing sites.
Update hook includes code that will set the text format for all basic pages on existing sites.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-276
=> Ensure basic_html is format for basic page intro text field

CHANGELOG.md, ecms_base/features/custom/ecms_speeches/config/install/core.entity_form_display.node.speech.default.yml, ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.default.yml, ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.teaser.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_text.yml, ecms_base/features/custom/ecms_speeches/config/install/field.storage.node.field_speech_text.yml, ecms_base/features/custom/ecms_speeches/config/install/views.view.speeches.yml, ecms_base/features/custom/ecms_speeches/ecms_speeches.info.yml, ecms_base/themes/custom/ecms/templates/content/node--speech--full.html.twig, ecms_base/themes/custom/ecms/templates/content/node--speech--teaser.html.twig, ecms_base/themes/custom/ecms/templates/views/views-view--speeches--page_1.html.twig, ecms_base/themes/custom/ecms/templates/views/views-view--speeches.html.twig
This adds the speeches to the profile as a feature.
- Updates the fields on the speeches
- Adds templates for them
- Adds speeches views
| Relevant links | 
| Development | https://thinkoomph.jira.com/browse/RIG-120
| Design | https://thinkoomph.jira.com/browse/RIG-260
=> Speech view, speech twig templates, updates to speech config

CHANGELOG.md
=> Prepare CHANGELOG for release 0.5.1

CHANGELOG.md, ecms_base/features/custom/ecms_vaccination_site/config/install/field.storage.node.field_vacsite_location_address.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.storage.node.field_vacsite_location_type.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/language.content_settings.taxonomy_term.vacsite_location_type.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/taxonomy.vocabulary.vacsite_location_type.yml
=> Prepare CHANGELOG for 0.5.2 release

CHANGELOG.md, ecms_base/modules/custom/ecms_languages/src/LanguageNegotiationSessionFix.php
Some paths were coming in empty, which resulted in "$parent=null" 
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-45
=> Add empty path check

CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_form_display.node.executive_order.default.yml, ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.media.executive_order_pdf.default.yml, ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.media.executive_order_pdf.media_library.yml, ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.node.executive_order.default.yml, ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.node.executive_order.teaser.yml, ecms_base/features/custom/ecms_executive_orders/config/install/field.field.node.executive_order.field_executive_order_text.yml, ecms_base/features/custom/ecms_executive_orders/config/install/field.storage.node.field_executive_order_text.yml, ecms_base/features/custom/ecms_executive_orders/config/install/pathauto.pattern.executive_orders.yml, ecms_base/features/custom/ecms_executive_orders/config/install/rabbit_hole.behavior_settings.node_type_executive_order.yml, ecms_base/features/custom/ecms_executive_orders/config/install/views.view.executive_orders.yml, ecms_base/features/custom/ecms_executive_orders/ecms_executive_orders.info.yml, ecms_base/features/custom/ecms_vaccination_site/ecms_vaccination_site.info.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/node--executive-order--full.html.twig, ecms_base/themes/custom/ecms/templates/content/node--executive-order--teaser.html.twig, ecms_base/themes/custom/ecms/templates/fields/field--node--executive-order.html.twig, ecms_base/themes/custom/ecms/templates/views/views-view--executive-orders--page_1.html.twig
This PR provides the theming for the executive order full listing, teaser, and node view.
Also included is some some contrib module changes to support the vaccination site as requested by Jason.
| Did you apply meaningful labels to the pull request? | yes/
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-47
=> Executive order full listing, teaser, and node view

CHANGELOG.md
=> Prepare changelog for release 0.5.3

ecms_base/modules/custom/ecms_migration/README.md
=> Update migration docs

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.media.file.field_file.yml
=> Allow zip for file media entities

CHANGELOG.md, composer.json, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_migration/README.md, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file.yml, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file_redirect.yml, ecms_base/modules/custom/ecms_migration/ecms_migration.module
Adds migrate_devel module.
Adds processing to the file paths.
Changes the redirect url from absolute to relative (on the _prepare_row hook).
Updates docs.
Includes update hook for existing sites.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-51
=> Update file and file redirect migrations

CHANGELOG.md, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file.yml
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-54
=> Add update hook for updated file migration

CHANGELOG.md
=> Prepare changelog for release 0.5.5

CHANGELOG.md, ecms_base/features/custom/ecms_location/config/install/paragraphs_translation_sync.location_list.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.accordion_builder.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.column_container.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.embed.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.file_list.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.formatted_text.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.gallery.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.gallery_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.icon_button.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.icon_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.media_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.numbered_step_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.text_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_icon.yml, ecms_base/features/custom/ecms_person/config/install/paragraphs_translation_sync.person_list.yml
Ran into issue where icon card paragraphs couldn't be translated, enabling the icon field itself to be translated (even though it rarely would be) fixed the issue.
Also enabled by default the sync settings for person and location.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-10
=> Enable translation for icon field

CHANGELOG.md, ecms_base/ecms_base.install
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-54
=> Update hook to rename files

CHANGELOG.md
=> Prepare changelog for release 0.5.6

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.embed.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.embed.preview.yml
=> Riga 56/embed format preview cleanup

CHANGELOG.md, ecms_base/features/custom/ecms_person/config/install/core.entity_form_display.node.person.default.yml, ecms_base/features/custom/ecms_person/config/install/core.entity_view_display.node.person.default.yml, ecms_base/features/custom/ecms_person/config/install/field.field.node.person.field_person_fax.yml, ecms_base/features/custom/ecms_person/config/install/field.field.node.person.field_person_mobile.yml, ecms_base/features/custom/ecms_person/config/install/field.storage.node.field_person_fax.yml, ecms_base/features/custom/ecms_person/config/install/field.storage.node.field_person_mobile.yml, ecms_base/themes/custom/ecms/templates/content/node--person--teaser.html.twig
This PR adds mobile and fax fields to person feature package.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-53
=> Add mobile and fax fields to person feature package.

CHANGELOG.md
=> Prepare CHANGELOG for 0.5.7 release

CHANGELOG.md, ecms_base/config/install/filter.format.basic_html.yml, ecms_base/ecms_base.install
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-57
=> Riga 57/add tables wysiwyg

CHANGELOG.md, ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_audience.yml, ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_form.yml, ecms_base/features/custom/ecms_publications/config/install/field.field.paragraph.publication_list.field_publication_list_language.yml, ecms_base/features/custom/ecms_publications/config/install/field.storage.paragraph.field_publication_list_language.yml, ecms_base/features/custom/ecms_publications/config/install/language.content_settings.paragraph.publication_list.yml, ecms_base/features/custom/ecms_publications/ecms_publications.info.yml
This PR resolves issues with publication list translation settings.
| Did you perform browser testing? | ye
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-64
=> Resolve issues with publication list translation settings

CHANGELOG.md
=> Prepare changelog for release 0.5.8

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/filter.format.paragraph_text.yml
=> Allow table tags within basic_html format

CHANGELOG.md
=> Prepare changelog for release 0.6.0

CHANGELOG.md
=> Prepare CHANGELOG for 0.6.1 release

CHANGELOG.md, composer.json, scripts/ci-develop.sh
Locks the ci-develop script to core 9.1.9 to address install error during tests.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-92
=> Update the ACSF module

CHANGELOG.md, ecms_base/config/install/node.type.webform.yml, ecms_base/config/install/pathauto.pattern.webform_nodes.yml, ecms_base/ecms_base.install
| Did you perform a self review first? | 
yes
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-78
https://thinkoomph.jira.com/browse/RIGA-41
=> Webform updates to display and path

CHANGELOG.md, ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publication_list.created.yml, ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publication_list.status.yml
This PR adds the remaining missing fields for publication list.
| Risk level | https://thinkoomph.jira.com/browse/RIGA-64
=> Fix additional issues with publication list translation settings.

CHANGELOG.md, composer.json
Adds the latest patch from issue http://drupal.org/node/2943344
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-18
=> Add global encrypt option to webform encrypt module

CHANGELOG.md
=> Prepare changelog for release 0.6.2

CHANGELOG.md
=> Prepare CHANGELOG for 0.6.3 release

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, ecms_base/themes/custom/ecms/templates/content/media--file.html.twig
Add the Media Entity Download module, enables it for new sites.
Update hook to install module on existing sites.
Updated Twig template to use the download path /media/{media_id}/download
Tested for translations, it handles automatically.
| Risk level | Low,
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-26
=> Add media entity download module and update links

CHANGELOG.md
=> Prepare changelog for release 0.6.4

ecms_base/config/install/user.role.anonymous.yml, ecms_base/config/install/user.role.authenticated.yml, ecms_base/ecms_base.install
=> Add media download permission to anon and auth users

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/media--file.html.twig
This solves the issue where someone wants to share a language specific link.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-26
=> Add language var to media download link

CHANGELOG.md, ecms_base/config/install/honeypot.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
Added a changelog note regarding user perms, those were merged in but forgot the log entry.
Updates the update hook to include the honeypot settings update, and uninstalls history module.
Disables views ui and history modules by default. Figuring we can enable views ui when needed, and it won't uninstall it.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-76
=> Install profile misc updates per Acquia recos

CHANGELOG.md
=> Prepare changelog for release 0.6.5

CHANGELOG.md, ecms_base/config/install/views.view.media.yml, ecms_base/ecms_base.install
=> Update default media view

CHANGELOG.md, ecms_base/ecms_base.install
=> Riga 76/disable history module

CHANGELOG.md
=> Prepare changelog for release 0.6.6

CHANGELOG.md
=> Prepare changelog for release 0.6.7

ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.accordion_builder.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.column_container.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.file_list.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.gallery.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.icon_button.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.icon_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.media_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.numbered_step_item.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.text_card.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.media.file.field_file_description.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.media.field_file_description.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/media--file.html.twig
=> Add file description field

CHANGELOG.md
=> Prepare changelog for release 0.6.8

CHANGELOG.md
=> Prepare CHANGELOG for release 0.6.9

CHANGELOG.md, composer.json, ecms_base/config/install/system.file.yml, ecms_base/ecms_base.install
Add a core patch to support filename transliteration on uploads.
Added system.file config to base install.
Added update hook.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-109
=> Add filename transliteration patch

CHANGELOG.md, ecms_base/config/install/user.role.form_author.yml, ecms_base/config/install/user.role.site_admin.yml, ecms_base/ecms_base.install, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.media_item.field_media_item.yml
Fix webform access permissions, make media item reference field translatable, uninstall http_cache_control module.
Addresses multiple tickets.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-129
https://thinkoomph.jira.com/browse/RIGA-127
=> Updates to roles, feature translation setting, uninstall module

CHANGELOG.md
=> Prepare changelog for release 0.7.2

CHANGELOG.md, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.default.yml, ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.media_library.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.media.file.field_file_list_weight.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.media.field_file_list_weight.yml, ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.features.yml, ecms_base/themes/custom/ecms/ecms.theme
Added sorting to file list by tag by adding a weight field to files.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-132
=> Add sorting to file list by tag paragraph

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/media--file.html.twig
This PR adds an edit link to media file for authenticated users.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-133
=> Add edit link to media file for authenticated users

CHANGELOG.md
=> Prepare changelog for release 0.7.3

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme
Add additional check for entity in media item preprocess.
| Did you perform a self review first? | no
| Did you perform browser testing? |no
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-138
=> Add additional check for entity in media item preprocess.

CHANGELOG.md
=> Prepare changelog for release 0.7.4

CHANGELOG.md, composer.json
Adds the asset injector module to the codebase.
tested locally and it installed fine.
| Unit/Functional tests reflect changes? |no
| Did you perform browser testing? | yes - confirmed install locally
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-146
=> Add asset injector module

CHANGELOG.md, composer.json
Module require only, installation will be manual on a per site basis.
Companion PR: https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/pull/133
| Unit/Functional tests reflect changes? |no
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-151
https://thinkoomph.jira.com/browse/RIGA-160
=> Add view database connector and entity print modules

CHANGELOG.md, composer.json
Adds a requirement for the ICal library. Resolves missing class error during Feeds import.
Add the requirement to the ecms_distribution repo and install.
Import a recent copy of the OLIS site database.
Run the feed at https://ecms-distribution.lndo.site/admin/content/feed
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-161
=> Require missing ICal library

CHANGELOG.md
=> Prepare changelog for release 0.7.7

CHANGELOG.md, composer.json, scripts/ci-develop.sh, scripts/develop.sh
=> Riga 6/develop updates

CHANGELOG.md, composer.json, ecms_base/ecms_base.install, ecms_base/features/custom/ecms_event/config/install/feeds.feed_type.ical_feed.yml
Updates the module (no db updates) and removes the mapping for "CREATED" (allow default current timestamp).
| Relevant links | [JIRA issue, bug reports, security alerts, etc.](https://thinkoomph.jira.com/browse/RIGA-166)
=> Update smart date module, update feed

CHANGELOG.md
=> Prepare changelog for release 0.7.8

CHANGELOG.md, docs/development.md, ecms_base/config/install/system.site.yml, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_api/src/EcmsApiInstall.php
Updates the system.site config file.
Adds install hook code to ensure value is set.
Adds update hook for existing sites.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-171
=> Update system site email value

CHANGELOG.md
=> Prepare CHANGELOG for 0.7.9 release

CHANGELOG.md, composer.json, ecms_base/modules/custom/ecms_blocks/src/Form/SearchStateBlockForm.php
=> Riga 175/webform security

CHANGELOG.md, ecms_base/config/install/views.view.content.yml, ecms_base/config/install/views.view.files.yml, ecms_base/config/install/views.view.media.yml, ecms_base/ecms_base.install
=> Update views, Prepare changelog for release 0.8.0

CHANGELOG.md
=> Prepare changelog for release 0.8.1

CHANGELOG.md
=> Prepare changelog for release 0.8.2

scripts/develop.sh
Some composer updates for the local develop script.
| Risk level |
=> Update core and behat versions for local script

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--header-image-action.html.twig, ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--page-title-with-photo.html.twig, ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--text-card-collection.html.twig
Adds the translate block links to other relevant templates.
Checkout branch and test locally logged in. You should see "Translate Block" links on all inline landing page blocks if the node has a translation:
| Risk level |
=> Add block translation links

CHANGELOG.md, composer.json, scripts/ci-develop.sh, scripts/develop.sh
Updates core to latest 9.2.x release (9.2.11).
Updated composer dependency so we stay within 9.2.x branch.
Updated shell scripts to use a core version variable, and set that to desired version 9.2.11.
Check out branch locally to run in the develop environment, or checkout a feature branch in ecms_distribution and test locally.
There are no core database updates.
| Risk level | medium
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-202
=> Riga 202/sa core 2022 001

CHANGELOG.md
=> Prepare changelog for release 0.8.3

CHANGELOG.md, ecms_base/config/install/views.view.media.yml, ecms_base/ecms_base.install
Updates the media view, includes update hook.
| Risk level |
=> Add media image download url

CHANGELOG.md, ecms_base/config/install/user.role.content_author.yml, ecms_base/config/install/user.role.content_publisher.yml, ecms_base/config/install/user.role.site_admin.yml, ecms_base/ecms_base.install
Permissions update and associated update hook to ensure author, publisher, and site admin users can all revert media revisions (that they have permission to edit).
Permissions were updated on COVID stage site to test:
https://covid.ri.gov/admin/content/media?name=&type=file&status=All&langcode=All
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-192
=> Riga 192/file revert permissions

CHANGELOG.md
=> Prepare changelog for release 0.8.4

CHANGELOG.md
=> Prepare changelog for release 0.8.5

CHANGELOG.md, composer.json, scripts/ci-develop.sh, scripts/develop.sh
Updates core to 9.3.7.
Updates Simple OAuth to 5.2 (4.x no longer supported).
Updates patch for core issue - profile base/parent inheritence.
Sending this to the DEV environment soon.
Test new site creation.
Test content creation.
Test Azure SSO (client will need to do this on stage).
Test block translations.
| Did you provide detail in the summary on how and where to test this branch? | Y
| Risk level | M
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-222
=> Core and Simple OAuth update

CHANGELOG.md
=> Prepare changelog for release 0.8.6

CHANGELOG.md, ecms_base/config/install/easy_breadcrumb.settings.yml
=> Hotfix for breadcrumb onfig

CHANGELOG.md, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
=> Riga 221/null config error

CHANGELOG.md
=> Prepare changelog for release 0.8.8

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, scripts/ci-develop.sh, scripts/develop.sh
=> Update core to 9.3.9

CHANGELOG.md
=> Prepare changelog for release 0.8.9

CHANGELOG.md, ecms_base/themes/custom/ecms/config/install/ecms.settings.yml, ecms_base/themes/custom/ecms/config/schema/ecms.schema.yml, ecms_base/themes/custom/ecms/ecms.theme, ecms_base/themes/custom/ecms/templates/content/media--file.html.twig, ecms_base/themes/custom/ecms/theme-settings.php
=> File link download global option

CHANGELOG.md
=> Prepare CHANGELOG for 0.9.1 release

CHANGELOG.md, composer.json, scripts/ci-develop.sh, scripts/develop.sh
=> Update core to 9.3.12

CHANGELOG.md
=> Prepare changelog for release 0.9.2

CHANGELOG.md, composer.json, ecms_base/config/install/language_cookie.negotiation.yml, ecms_base/ecms_base.install, ecms_base/themes/custom/ecms/ecms.theme
Tracked the original issue down to a JS library being pulled in based on a dependency in the smart_date module.
It looks like that package has been updated or the JS source resolved but we needed to update smart date anyway so pushing that.
Included some minor PHP bug fixes as well, and an update to the language config defaults we didn't backport into the profile.
| Risk level |
=> JS aggregate error - update Smart Date

CHANGELOG.md
=> Prepare changelog for release 0.9.3

CHANGELOG.md
=> Prepare changelog for release 0.9.5

CHANGELOG.md, composer.json
=> Add search api exclude requirement

CHANGELOG.md
=> Prepare changelog for release 0.9.6

CHANGELOG.md, composer.json
=> Add big menu

CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_database_search/config/install/search_api.index.database.yml, ecms_base/features/custom/ecms_executive_orders/config/install/field.field.node.executive_order.field_executive_order_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.text_card_collection.field_collection_description.yml, ecms_base/features/custom/ecms_notification/config/install/field.field.node.notification.field_notification_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.embed.field_embed_content.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.formatted_text.field_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.gallery_item.field_gallery_item_caption.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.text_card.field_text.yml, ecms_base/features/custom/ecms_promotions/config/install/field.field.node.promotions.field_promotion_text.yml, ecms_base/features/custom/ecms_solr_search/config/install/search_api.index.acquia_search_index.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_text.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.field.node.vaccination_site.field_vacsite_body.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.field.node.vaccination_site.field_vacsite_spec_instructions.yml, scripts/ci-develop.sh, scripts/develop.sh
This updates core to 9.3.15.
It also updates config for the distribution text formats "allowed_formats" settings, which was modified in the recent upgrade of that module (1.5).
Search API config is also updated for the two distribution indexes to include the newly introduced `track_changes_in_references` config value.
This is on STAGE for review: https://dem.test-riecms.acsitefactory.com/
https://covid.test-riecms.acsitefactory.com/
| Risk level | L
| …
=> Update core and some contrib settings

CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_executive_orders/config/install/field.field.node.executive_order.field_executive_order_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.header_image_action.field_hia_text.yml, ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.text_card_collection.field_collection_description.yml, ecms_base/features/custom/ecms_notification/config/install/field.field.node.notification.field_notification_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.embed.field_embed_content.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.formatted_text.field_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.gallery_item.field_gallery_item_caption.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.icon_card.field_text.yml, ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.text_card.field_text.yml, ecms_base/features/custom/ecms_promotions/config/install/field.field.node.promotions.field_promotion_text.yml, ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_text.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.field.node.vaccination_site.field_vacsite_body.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.field.node.vaccination_site.field_vacsite_spec_instructions.yml, ecms_base/features/custom/ecms_vaccination_site/config/install/field.storage.node.field_vacsite_office_hours.yml, scripts/ci-develop.sh, scripts/develop.sh
=> Riga 278/update core

CHANGELOG.md
=> Prepare changelog for release 0.9.8

.github/workflows/develop.yml, CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_basic_page/config/install/pathauto.pattern.pages.yml, ecms_base/features/custom/ecms_event/config/install/pathauto.pattern.events.yml, ecms_base/features/custom/ecms_executive_orders/config/install/pathauto.pattern.executive_orders.yml, ecms_base/features/custom/ecms_hotel/config/install/pathauto.pattern.accommodations.yml, ecms_base/features/custom/ecms_location/config/install/pathauto.pattern.locations.yml, ecms_base/features/custom/ecms_person/config/install/pathauto.pattern.people.yml, ecms_base/features/custom/ecms_press_release/config/install/pathauto.pattern.press_releases.yml, ecms_base/features/custom/ecms_projects/config/install/pathauto.pattern.projects.yml, ecms_base/features/custom/ecms_speeches/config/install/pathauto.pattern.speeches.yml
June module updates.
Add back in functional tests via results of [RIGA-270](https://thinkoomph.jira.com/browse/RIGA-270)
| Risk level |
=> June modules part 3

CHANGELOG.md
=> Prepare changelog for release 0.9.9

CHANGELOG.md
=> Prepare changelog for release 0.9.10

CHANGELOG.md, composer.json, ecms_base/config/install/user.role.site_admin.yml, ecms_base/features/custom/ecms_executive_orders/config/install/pathauto.pattern.executive_orders.yml, scripts/ci-develop.sh, scripts/develop.sh
Updates the core version to 9.3.19
Updates paragraphs patch to resolve version reporting issue.
Minor config updates for permissions and pathauto
These changes are live on the TESET site, use covid:
https://covid.test-riecms.acsitefactory.com/user/login?showcore
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-285
https://thinkoomph.jira.com/browse/RIGA-293
=> Core update 9.3.19 and misc profile updates

ecms_base/ecms_base.install
=> Add update hook for user role

CHANGELOG.md
=> Prepare changelog for release 0.9.11

.github/workflows/develop.yml, CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_solr_search/config/install/views.view.acquia_search.yml, scripts/ci-develop.sh, scripts/develop.sh
- Updates drupal/core 9.3.19 => 9.4.5
- Add increased memory limits and timeouts to .env file.
- Updates core patch for issue 1356276.
- Saves config for Acquia search view after db update.
- Comments out functional tests from develop script, so they won't run temporarily.
| Did you provide detail in the summary on how and where to test this branch? |N
| Risk level |M
| Relevant links | [RIGA-282](https://thinkoomph.jira.com/browse/RIGA-282) / [RIGA-297](https://thinkoomph.jira.com/browse/RIGA-297)
=> Update drupal/core => 9.4.5

CHANGELOG.md, composer.json, scripts/develop.sh
=> PHP 8 updates

CHANGELOG.md
=> Prepare changelog for release 0.9.14

CHANGELOG.md
=> Prepare changelog for release 0.9.15

CHANGELOG.md, composer.json, ecms_base/config/install/views.view.files.yml, ecms_base/ecms_base.install
=> Riga 312/update unsupported moules

CHANGELOG.md, composer.json, ecms_base/modules/custom/ecms_layout/ecms_layout.module, ecms_base/themes/custom/ecms/templates/layout/tabs.html.twig
This PR adds layout_builder_tabs and the necessary patch. The module will not be included in default installs.
| Risk level | L
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-317
=> Add Layout Builder Tabs contrib module

CHANGELOG.md
=> Prepare changelog for release 0.9.16

CHANGELOG.md, ecms_base/features/custom/ecms_solr_search/config/install/search_api.index.acquia_search_index.yml
=> Riga 328/nov contrib mods 1

CHANGELOG.md, composer.json
Updated contribute module:
Acquia Connector 3.0
Recommended version: 4.0 (2022-Oct-19)
| Risk level |
=> Contribute Module Update Acquia Connector

CHANGELOG.md, ecms_base/features/custom/ecms_event/config/install/core.entity_form_display.node.event.default.yml
=> Update form display

CHANGELOG.md
=> Prepare changelog for release 0.9.17

CHANGELOG.md
=> Prepare changelog for release 0.9.18

CHANGELOG.md, composer.json
=> Allowed formats patch

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.theme
Updates paragraph preprocess function, 
Instead of returning from function if there are no publications to list, always check for selector form.
- visit page http://olisfinal.test-riecms.acsitefactory.com/resources
- try selecting option "EMTs"
- verify selector form is still available despite no search results
- verify message appears "No results for this search"
| Relevant links | [RIGA-360](https://thinkoomph.jira.com/browse/RIGA-360)
=> Fix disappearing dropdown selector

CHANGELOG.md, composer.json, ecms_base/ecms_base.install
- Adds these modules to composer.json:
- "drupal/entity_usage": "^2.0@beta"
- "drupal/focal_point": "^2.0.1"
- "drupal/iek": "^1.3"
- Adds db update hook `ecms_base_update_9100` to install new modues
| Relevant links | [RIGA-401](https://thinkoomph.jira.com/browse/RIGA-401)
=> Install modules entity_usage, focal_point, and iek

CHANGELOG.md, composer.json
- Update version constrain for drupal/acsf 2.73 => ^2.75
| Risk level |
| Relevant links | [RIGA-409](https://thinkoomph.jira.com/browse/RIGA-409)
=> August Module Updates pt2-2

CHANGELOG.md, ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--header-image-action.html.twig
Adds check to Twig template to avoid unrouted links error.
Test newest revision of landing page on DOIT test site
| Relevant links | [RIGA-429](https://thinkoomph.jira.com/browse/RIGA-429)
=> Add check for unrouted links to fix layout builder error

ecms_base/config/install/crop.type.focal_point.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
Strip UUID form config to prevent install error on multisite
Change update hooks to import cpnfig before installing modules
Add to .info file
| `CHANGELOG` reflects changes? |N
| Relevant links | [RIGA-401](https://thinkoomph.jira.com/browse/RIGA-401)
=> Fix Focal Point config

CHANGELOG.md, ecms_base/config/install/key.key.openid_connect_windows_aad_key.yml, ecms_base/config/install/openid_connect.client.windows_aad.yml, ecms_base/config/install/openid_connect.settings.yml, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php, ecms_base/modules/custom/ecms_migration/tests/src/Unit/Form/EcmsMigrationConfigFormTest.php
=> Save changed config files for openid_connect update

CHANGELOG.md
=> Prepare changelog for release 0.11.0

CHANGELOG.md, composer.json
This adds the path_redirect_import module to the profile.
Confirm the module is available to be installed.
n/a
| Relevant links | [RIGA-448](https://thinkoomph.jira.com/browse/RIGA-448)
=> Add path redirect import module

CHANGELOG.md, ecms_base/config/install/scheduled_transitions.settings.yml, ecms_base/modules/custom/ecms_workflow/ecms_workflow.info.yml
Fixed the permissions error during site installation
`drush si ecms_acquia` and confirm no errors.
n/a
| Documentation reflects changes? |n/a
| Unit/Functional tests cover changes? |yes
| Relevant links | [RIGA-458](https://thinkoomph.jira.com/browse/RIGA-458)
=> RIGA-458/Fixed the config installation

CHANGELOG.md, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_ckeditor/ecms_ckeditor.ckeditor5.yml, ecms_base/modules/custom/ecms_ckeditor/ecms_ckeditor.info.yml
Add a custom module that will enable the ckeditor column widths plugin.
Edit a table in ckeditor. Hover the mouse over a column bar and the cursor should change to indicate it is resizable.
| Relevant links | [RIGA-467](https://thinkoomph.jira.com/browse/RIGA-467)
=> Add ckeditor column width plugin

CHANGELOG.md, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_file.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_file_es.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_link.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_media.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_media_es.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_redirect.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_redirect_es.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration_group.files_json_to_resource_media.yml
Update the dependencies of the health migration custom configuration. Added the `disease` field to the migration.
Rollback and re-import.
n/a
| Relevant links | [RIGA-462](https://thinkoomph.jira.com/browse/RIGA-462)
=> Updated the health file migration code

ecms_base/modules/custom/ecms_api_notification_publisher/tests/src/Unit/NotificationPublisherTest.php, ecms_base/modules/custom/ecms_api_publication_publisher/tests/src/Unit/PublicationPublisherTest.php, ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php, ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiCreateNotifications.php, ecms_base/modules/custom/ecms_api_recipient/src/Plugin/QueueWorker/NotificationCreationQueueWorker.php, ecms_base/modules/custom/ecms_languages/src/Form/EcmsLanguageSettings.php
This fixes linting errors that were discovered in phpcs during the 1.0.2 release process.
=> Fixed linting errors

CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
Added an rc version of the Media PDF Thumbnail module.
| Relevant links | [RIGA-475](https://thinkoomph.jira.com/browse/RIGA-475)
=> Riga 475/add media pdf thumbnail module

CHANGELOG.md, composer.json
Includes the security kit module for all sites.
n/a
| Relevant links | [RIGA-508](https://thinkoomph.jira.com/browse/RIGA-508)
=> Added the security kit module to the codebase

CHANGELOG.md, ecms_base/features/custom/ecms_basic_page/config/install/field.field.node.basic_page.field_basic_page_body.yml
| Unit/Functional tests cover changes? | N/A
| Relevant links | [RIGA-510](https://thinkoomph.jira.com/browse/RIGA-510)
=> Update intro text field for basic page

CHANGELOG.md, composer.json
Add HAL module (version 2.0.2)
| Relevant links | [RIGA-522](https://thinkoomph.jira.com/browse/RIGA-522)
=> Add HAL module

ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_agency.yml
=> Add missing option

CHANGELOG.md, composer.json, ecms_base/features/custom/ecms_press_release/config/install/core.entity_form_display.node.press_release.default.yml, ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.default.yml, ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.teaser.yml, ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_agency.yml, ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_body.yml, ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_source.yml, ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_agency.yml, ecms_base/features/custom/ecms_press_release/ecms_press_release.info.yml
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/510
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/509
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/507
=> Release Candidate for 1.0.5

ecms_base/features/custom/ecms_emergency_notification/ecms_emergency_notification.info.yml
The feature version requirement had a syntax error. This PR fixes it.
=> Fix error in version requirement

ecms_base/config/install/google_translator.settings.yml
| `CHANGELOG` reflects changes? | no
| Did you provide detail in the summary on how and where to test this branch? | info in first PR https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/511
| Relevant links | RIGA-483
=> Update list of languages

ecms_base/config/install/google_translator.settings.yml
Reverts State-of-Rhode-Island-eCMS/ecms_profile#516
=> Revert "Update list of languages"

.github/workflows/develop.yml, CHANGELOG.md, composer.json, ecms_base/config/install/google_translator.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_form_display.node.emergency_notification.default.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_view_display.node.emergency_notification.default.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_view_display.node.emergency_notification.teaser.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_background_color.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_expire_date.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_message.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_weight.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_background_color.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_expire_date.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_message.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_weight.yml, ecms_base/features/custom/ecms_emergency_notification/config/install/node.type.emergency_notification.yml, ecms_base/features/custom/ecms_emergency_notification/ecms_emergency_notification.features.yml, ecms_base/features/custom/ecms_emergency_notification/ecms_emergency_notification.info.yml, ecms_base/themes/custom/ecms/config/optional/block.block.googletranslator.yml, ecms_base/themes/custom/ecms/config/optional/block.block.languageswitcher.yml, ecms_base/themes/custom/ecms/ecms.libraries.yml, scripts/ci-develop.sh, scripts/develop.sh
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/513
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/512
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/511
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/515
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/518
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/517
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/519
=> Release Candidate for 1.0.6

CHANGELOG.md, ecms_base/modules/custom/ecms_icon_library/src/Plugin/Field/FieldFormatter/EcmsIconLibraryFormatter.php, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-button.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-card.html.twig
This fixes the formatter to properly utilize a render array, fixing the 500 error while editing the paragraph.
- Create a new basic page
- Add a new icon button paragraph
- Save. Confirm the icon loads.
- Edit the node, confirm the admin form loads
n/a
| Unit/Functional tests cover changes? |n/a
| Relevant links | [RIGA-546](https://thinkoomph.jira.com/browse/RIGA-546)
=> Fixed the icon formatter

CHANGELOG.md, ecms_base/config/install/google_translator.settings.yml, ecms_base/ecms_base.install
Updates the list of translation options for all sites.
| Relevant links | [RIGA-548](https://thinkoomph.jira.com/browse/RIGA-548)
=> Update the list of google translation options

CHANGELOG.md, ecms_base/config/install/google_translator.settings.yml, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_icon_library/src/Plugin/Field/FieldFormatter/EcmsIconLibraryFormatter.php, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-button.html.twig, ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--icon-card.html.twig
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/522
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/520
=> Release Candidate for 1.0.7

.github/workflows/develop.yml, CHANGELOG.md, composer.json, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_file.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_file_es.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_link.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_media.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_resource_media_es.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_redirect.yml, ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_redirect_es.yml, ecms_base/modules/custom/ecms_languages/src/LanguageNegotiationSessionFix.php, phpcs-ci.xml, phpcs.xml
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/525
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/526
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/528
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/529
=> Release Candidate for 1.0.8

CHANGELOG.md, ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisherInstall.php, ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiRecipientInstall.php, ecms_base/modules/custom/ecms_feeds/src/Feeds/Parser/EcmsPressReleaseParser.php, ecms_base/modules/custom/ecms_layout/ecms_layout.module, ecms_base/themes/custom/ecms/ecms.theme
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/533
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/534
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/532
- https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/pull/531
=> Release Candidate for 1.0.9 

CHANGELOG.md, ecms_base/modules/custom/ecms_api/src/EcmsApiBase.php, ecms_base/modules/custom/ecms_api_press_release_publisher/ecms_api_press_release_publisher.module, ecms_base/modules/custom/ecms_api_publisher/config/install/ecms_api_publisher.settings.yml, ecms_base/modules/custom/ecms_api_publisher/config/schema/ecms_api_publisher.schema.yml, ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php, ecms_base/modules/custom/ecms_api_recipient/config/install/user.role.ecms_api_recipient.yml, ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiRecipientInstall.php, ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php
Initial work to get the syndication working on the lower environments.
Enable the `ecms_api_recipient` module on the first site and configure it to allow press releases.
Enable the `ecms_api_publisher` module on the second site and configure it to connect to the first and send press releases.
Create a press release on the second site and confirm that it is successfully created on the first site. This occurs during cron or can be manually triggered.
| …
=> Riga 564/syndication

CHANGELOG.md, ecms_base/themes/custom/ecms/ecms.libraries.yml
| Risk level |
| Relevant links | [RIGA-555](https://thinkoomph.jira.com/browse/RIGA-555) [](url)
=> RIGA-555: Update the Patternlab version

CHANGELOG.md, ecms_base/modules/custom/ecms_api/src/EcmsApiBase.php, ecms_base/modules/custom/ecms_api_press_release_publisher/ecms_api_press_release_publisher.module, ecms_base/modules/custom/ecms_api_publisher/config/install/ecms_api_publisher.settings.yml, ecms_base/modules/custom/ecms_api_publisher/config/schema/ecms_api_publisher.schema.yml, ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php, ecms_base/modules/custom/ecms_api_recipient/config/install/user.role.ecms_api_recipient.yml, ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiRecipientInstall.php, ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php, ecms_base/modules/custom/ecms_authentication/ecms_authentication.post_update.php, ecms_base/themes/custom/ecms/ecms.libraries.yml
=> Merging the RC 1.1.0 branch

ecms_base/themes/custom/ecms/ecms.libraries.yml
Bumps the library version number for cache clearing as this is shipping with this PR: https://github.com/State-of-Rhode-Island-eCMS/ecms_patternlab/pull/186/files
=> Bumped the library version

ecms_base/themes/custom/ecms/ecms.libraries.yml
Bumps all theme library versions to clear caches on deploy
=> Updated all library versions

ecms_base/modules/custom/ecms_languages/ecms_languages.module
A continuation of #549 as I forgot to wrap the code in a conditional.
=> Added conditional to prevent php warnings

ecms_base/modules/custom/ecms_languages/ecms_languages.module
=> Fixed isset call

ecms_base/modules/custom/ecms_languages/ecms_languages.module
Fixes the hook name to be the proper syntax.
=> Fix hook name

ecms_base/modules/custom/ecms_languages/src/Plugin/Block/LanguageSelector.php
Adds a missing library to help fix the cache issues.
=> Added additional library

ecms_base/modules/custom/ecms_languages/ecms_languages.libraries.yml, ecms_base/modules/custom/ecms_languages/ecms_languages.module, ecms_base/modules/custom/ecms_languages/src/Plugin/Block/LanguageSelector.php
Changes the js to remove the inline element and adding a new custom library.
=> Change the library

.github/workflows/develop.yml, ecms_base/modules/custom/ecms_api/tests/src/Unit/EcmsApiBaseTest.php, ecms_base/modules/custom/ecms_api_publication_publisher/tests/src/Unit/PublicationPublisherTest.php, ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiPublisherTest.php, ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Entity/EcmsApiSiteTest.php, ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php, ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/EcmsApiRecipientInstallTest.php, ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/EcmsApiRecipientRegisterTest.php, ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/Form/EcmsApiRecipientConfigFormTest.php, ecms_base/modules/custom/ecms_languages/tests/src/Unit/LanguageNegotiationSessionFixTest.php, ecms_base/modules/custom/ecms_migration/tests/src/Unit/Form/EcmsMigrationConfigFormTest.php, ecms_base/modules/custom/ecms_workflow/tests/src/Unit/EcmsWorkflowBundleCreateTest.php, scripts/develop.sh
Updates development and ci environments for php 8.3
| Risk level |
=> Updated php versions

ecms_base/themes/custom/ecms/ecms.theme
Fixes CI errors that appeared in the rc/1.1.2 branch.
=> Fixed CI errors

ecms_base/features/custom/ecms_press_release/ecms_press_release.module
The URL validation was throwing errors. This updates the logic to ensure http is included and wraps the exception in a try/catch block to prevent a WSOD.
[RIGA-571](https://thinkoomph.jira.com/browse/RIGA-571)
=> Fixed url validation

.github/workflows/develop.yml, ecms_base/ecms_base.install
Fixes a php error in the update hook.
[RIGA-485](https://thinkoomph.jira.com/browse/RIGA-485)
=> Fixed update hook

ecms_base/themes/custom/ecms/templates/content/node--emergency-notification--teaser.html.twig
Using the label as the block header
| `CHANGELOG` reflects changes? | no
| Relevant links | RIGA-485
=> update label variable to be more unique

ecms_base/modules/custom/ecms_distribution/ecms_distribution.module
Fixes a php error discovered during php 8.3 testing
[RIGA-529](https://thinkoomph.jira.com/browse/RIGA-529)
=> Fixed php error

ecms_base/themes/custom/ecms/ecms.libraries.yml
Bumps the library versions to clear Drupal caching.
=> Updated library version numbers

ecms_base/themes/custom/ecms/ecms.libraries.yml
Bumps library versions to ensure caches are cleared on deployment.
=> Bumped library versions to clear cache

CHANGELOG.md, ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_agency.yml
update press release agency field -  Set Press Release Agency field to required 
[RIGA-605](https://thinkoomph.jira.com/browse/RIGA-605)
=> Riga 605/update press release agency field

ecms_base/modules/custom/ecms_api_emergency_notification_publisher/src/EmergencyNotificationPublisher.php, ecms_base/modules/custom/ecms_api_emergency_notification_publisher/tests/src/Unit/EmergencyNotificationPublisherTest.php
This adds syndication of unpublished emergency notifications.
[RIGA-512](https://thinkoomph.jira.com/browse/RIGA-512)
=> Added unpublishing to syndication

CHANGELOG.md, composer.json, scripts/ci-develop.sh, scripts/develop.sh
Adds the purge_file module to the profile.
Also, updates the minimum Drupal core version in both ci and develop scripts.
[RIGA-624](https://thinkoomph.jira.com/browse/RIGA-624)
=> Added purge_file

CHANGELOG.md, ecms_base/config/install/user.role.content_publisher.yml, ecms_base/ecms_base.install
Updated Content Publisher permissions to syndicate Press Releases.
| Did you provide detail in the summary on how and where to test this branch? |no
| Relevant links | [RIGA-630](https://thinkoomph.jira.com/browse/RIGA-630)
=> permission updated

CHANGELOG.md, ecms_base/features/custom/ecms_press_release/config/install/core.entity_form_display.node.press_release.default.yml
Disables the language and promotions form field for the press release content type.
| Did you provide detail in the summary on how and where to test this branch? |no
| Relevant links | [RIGA-639](https://thinkoomph.jira.com/browse/RIGA-639), [RIGA-617](https://thinkoomph.jira.com/browse/RIGA-617)
=> Riga 639/update press release form

ecms_base/themes/custom/ecms/ecms.libraries.yml
Updated Library Versions for [RIGA-636](https://thinkoomph.jira.com/browse/RIGA-636)
=> updated library versions

CHANGELOG.md, composer.json, ecms_base/modules/custom/ecms_icon_library/ecms_icon_library.info.yml, ecms_base/modules/custom/ecms_icon_library/src/Plugin/Field/FieldFormatter/EcmsIconLibraryFormatter.php
This removes the unnecessary reliance on CURL to show an image preview.
[RIGA-607](https://thinkoomph.jira.com/browse/RIGA-607)
=> Riga 607/remove curl reliance

.ddev/commands/web/phpcs, .ddev/commands/web/phpunit, ecms_base/modules/custom/ecms_api_publisher/Commands/EcmsApiPublisherCommand.php, ecms_base/modules/custom/ecms_api_publisher/drush.services.yml, ecms_base/modules/custom/ecms_api_publisher/src/Commands/EcmsApiPublisherCommand.php, ecms_base/modules/custom/ecms_api_recipient/drush.services.yml, ecms_base/modules/custom/ecms_api_recipient/src/Commands/EcmsApiRecipientCommand.php, phpcs.xml
Adds drush commands that will update entities when staging sites down.
[RIGA-643](https://thinkoomph.jira.com/browse/RIGA-643)
=> Added new drush command to update publisher entitiy

CHANGELOG.md, composer.json, ecms_base/config/install/password_policy.password_policy.password_rules.yml, ecms_base/config/install/password_policy.settings.yml, ecms_base/ecms_base.info.yml, ecms_base/ecms_base.install
- [RIGA-600]( https://thinkoomph.jira.com/browse/RIGA-600): Install module password policy -
- [ RIGA-628]( https://thinkoomph.jira.com/browse/RIGA-628): Install module ultimate cron
=> Module install password_policy and ultimate_cron

ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file.yml, ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file_redirect.yml
Fixes deprecated plugin usage in the custom migration configurations.
See: https://www.drupal.org/node/3255994
[RIGA-603](https://thinkoomph.jira.com/browse/RIGA-603)
=> Updated use of deprecated plugin

ecms_base/modules/custom/ecms_migration/ecms_migration.module
Fixes an incorrect usage of a non-static method during the file redirect import.
[RIGA-603](https://thinkoomph.jira.com/browse/RIGA-603)
=> Fixed incorrect method usage

ecms_base/modules/custom/ecms_api_publisher/src/Commands/EcmsApiPublisherCommand.php, ecms_base/modules/custom/ecms_api_recipient/src/Commands/EcmsApiRecipientCommand.php, ecms_base/modules/custom/ecms_blocks/src/Form/SearchBlockForm.php
Adds the `client_id` to the entity update commands.
[RIGA-643](https://thinkoomph.jira.com/browse/RIGA-643)
=> Added the client id to the script

CHANGELOG.md, composer.json
Fixed build Error
https://thinkoomph.jira.com/browse/RIGA-703
=> RIGA 703/codesniffer build error

CHANGELOG.md, composer.json
update simple sitemap [SA-CONTRIB-2025-083](https://www.drupal.org/sa-contrib-2025-083)
https://thinkoomph.jira.com/browse/RIGA-659
=> RiGA 659/simple sitemap security update

ecms_base/themes/custom/ecms/templates/views/views-view.html.twig
This adds the `views-view.html.twig` file to the custom theme and prints the view title as an `<h1>` tag.
[RIGA-488](https://thinkoomph.jira.com/browse/RIGA-488)
=> Updated the views-view template to print the title as h1

ecms_base/themes/custom/ecms/components/01-molecules/teaser-executive-order/teaser-executive-order.twig, ecms_base/themes/custom/ecms/components/01-molecules/teaser-speech/teaser-speech.twig
Removes an old Pattern Lab component reference and includes the new single directory component instead.
[RIGA-737](https://thinkoomph.jira.com/browse/RIGA-737)
=> Fixed dangling pattern lab component reference
