State-of-Rhode-Island-eCMS/ecms_profile

CHANGELOG.md
composer.json
ecms_base/config/install/block_content.type.basic.yml
ecms_base/config/install/editor.editor.basic_html.yml
ecms_base/config/install/editor.editor.full_html.yml
ecms_base/config/install/filter.format.basic_html.yml
ecms_base/config/install/filter.format.full_html.yml
ecms_base/config/install/filter.format.restricted_html.yml
ecms_base/config/install/node.settings.yml
ecms_base/config/install/system.cron.yml
ecms_base/config/install/system.site.yml
ecms_base/config/install/system.theme.yml
ecms_base/config/install/user.role.administrator.yml
ecms_base/config/install/user.role.anonymous.yml
ecms_base/config/install/user.role.authenticated.yml
ecms_base/config/install/user.settings.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install
tests/src/Functional/AllProfileInstallationTestsAbstract.php

This updates the ecms_base profile to install basic required modules and themes to get started. Most of the modules and configuration were borrowed from the standard installation profile. I purposely left out some that I thought were not necessary like the comments module. No fields were installed as these _should_ be managed through the features module. The user registration default configuration was set to disallow user registrations.
| Did you perform browser …

Updated the ecms_base profile to install some basic modules & config.

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
phpunit.xml
tests/src/Functional/AllProfileInstallationTestsAbstract.php

This will add the webform as a requirement and installs the webform and the webform_ui modules on installation.
| Relevant links | [RIG-32](https://thinkoomph.jira.com/browse/rig-32)

Added webform as a requirement for the ecms_base profile

---

CHANGELOG.md
docs/development.md
docs/features.md
ecms_base/ecms_base.info.yml
ecms_base/features/custom/ecms_press_release/config/install/core.base_field_override.node.press_release.promote.yml
ecms_base/features/custom/ecms_press_release/config/install/core.entity_form_display.node.press_release.default.yml
ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.default.yml
ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.teaser.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_body.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_date.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_links.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_source.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_press_release_body.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_press_release_date.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_press_release_links.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_press_release_source.yml
ecms_base/features/custom/ecms_press_release/config/install/node.type.press_release.yml
ecms_base/features/custom/ecms_press_release/ecms_press_release.features.yml
ecms_base/features/custom/ecms_press_release/ecms_press_release.info.yml
ecms_base/tests/src/Functional/InstallationTest.php
tests/src/Functional/AllProfileInstallationTestsAbstract.php

This expands upon the PR in #7 and adds the press release content type as a feature and installs the feature module on profile installation.
Additional documentation was added to explain the use of features in this process. 
| Relevant links | [RIG-33](https://thinkoomph.jira.com/browse/rig-33)

Add the press release content type as a feature

---

CHANGELOG.md
docs/features.md
ecms_base/ecms_base.info.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.base_field_override.node.basic_page.promote.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_view_display.node.basic_page.default.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_view_display.node.basic_page.teaser.yml
ecms_base/features/custom/ecms_basic_page/config/install/field.field.node.basic_page.field_basic_page_body.yml
ecms_base/features/custom/ecms_basic_page/config/install/field.storage.node.field_basic_page_body.yml
ecms_base/features/custom/ecms_basic_page/config/install/node.type.basic_page.yml
ecms_base/features/custom/ecms_basic_page/ecms_basic_page.features.yml
ecms_base/features/custom/ecms_basic_page/ecms_basic_page.info.yml
tests/src/Functional/AllProfileInstallationTestsAbstract.php

This adds the basic page content type as a feature module to the code base and installs it by default. The Flexible Content field was purposely left off as those need to be defined yet.
| Relevant links | [RIG-39](https://thinkoomph.jira.com/browse/rig-39)

Add the Basic page content feature to the profile

---

.github/workflows/develop.yml
CHANGELOG.md
scripts/develop.sh

Disable xdebug and break the testing out by group. This _seems_ to have improved functional testing performance from 30-40 minutes to ~5 minutes.
| Did you perform browser testing? | n/a

Testing performance fixes

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_recipient/README.md
ecms_base/modules/custom/ecms_api_recipient/config/schema/ecms_api_recipient.schema.yml
ecms_base/modules/custom/ecms_api_recipient/ecms_api_recipient.links.menu.yml
ecms_base/modules/custom/ecms_api_recipient/ecms_api_recipient.routing.yml
ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/Functional/InstallationTest.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/Form/EcmsApiRecipientConfigFormTest.php

This is a continuation of #21 and adds a new configuration form that allows an administrator to select the content types they would like to receive content syndication for. This will save the configuration and will update the ecms_api_recipient role permissions and provide the ceate node type and edit own node type permissions for the selected content types. This will then allow syndication to publish these content types.
| …

Add configuration form enabling content types for the API

---

CHANGELOG.md
phpcs.xml
scripts/develop.sh

This fixes the develop.sh script to properly pull in the pattern lab repository and place it into the custom theme using the installer paths.
| Relevant links | [RIG-37](https://thinkoomph.jira.com/browse/rig-37)

Fix the develop script to properly pull in the pattern lab repository.

---

CHANGELOG.md
composer.json
docs/development.md
scripts/develop.sh

This updates the develop script to symlink the `ecms_patternlab` git repository if one exists on the same directory hierarchy as the `ecms_profile` directory. This will allow for simultaneous development of both the theme and the patterns within the Drupal environment.
In order to get this working, I needed to remove the dependency on the pattern lab repository to allow local requirements. We will need to update the `ecms_distribution` to require the pattern lab repository before the next deployment.
| …

Update the develop script to allow for Pattern Lab development

---

CHANGELOG.md
composer.json
docs/development.md
ecms_base/ecms_base.info.yml
ecms_base/themes/custom/ecms/ecms.info.yml
ecms_base/themes/custom/ecms/ecms.libraries.yml

This PR adds the components module to the default install. The components module is required to integrate Pattern Lab with Drupal. Some additional changes are included that connect the Drupal theme to the ECMS pattern lab repository. 
| Relevant links | https://thinkoomph.jira.com/browse/RIG-37

Install components and connect pattern lab assets to theme

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_recipient/config/install/ecms_api_recipient.settings.yml
ecms_base/modules/custom/ecms_api_recipient/config/install/user.role.ecms_api_recipient.yml
ecms_base/modules/custom/ecms_api_recipient/ecms_api_recipient.info.yml
ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/Functional/InstallationTest.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/Form/EcmsApiRecipientConfigFormTest.php

This updates the ecms api recipient module to enable the notification content type by default and updates the configuration form to allow the ecms_api_recipient role to publish nodes using the editorial workflow.
| Relevant links | [RIG-76](https://thinkoomph.jira.com/browse/rig-76)

Update the ecms_api_recipient installation configuration

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_api/ecms_api.install
ecms_base/modules/custom/ecms_api_publisher/README.md
ecms_base/modules/custom/ecms_api_publisher/config/install/ecms_api_publisher.settings.yml
ecms_base/modules/custom/ecms_api_publisher/config/schema/ecms_api_publisher.schema.yml
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.install
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.module
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.permissions.yml
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.routing.yml
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.services.yml
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiSyndicate.php
ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
ecms_base/modules/custom/ecms_api_publisher/src/Plugin/QueueWorker/EcmsApiSyndicateQueueWorker.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiPublisherTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiSyndicateTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Plugin/QueueWorker/EcmsApiSyndicateQueueWorkerTest.php
ecms_base/modules/custom/ecms_api_recipient/ecms_api_recipient.install
ecms_base/modules/custom/ecms_authentication/ecms_authentication.module
ecms_base/modules/custom/ecms_workflow/ecms_workflow.module
phpcs.xml
phpunit.xml

Apologies, this functionality got a little large. This does the following:
1. Coding standards: the phpcs.xml file was not configured properly and was skipping .module/.install/etc. extensions. That has been added and those standards have been fixed.
2. Add a new `ecms_api_publisher.publisher` service that manages posting the node to the recipient site.
3. Add another new `ecms_api_publisher.syndicate` that manages collecting new nodes and adding them to the queue api for publishing with the publishing site's cron job.
4. Add a new confirm form that will collect the queued content and add those to a batch process for immediate processing.
This does not currently contain the workflow logic of determining if a node should be published before syndication. …

Add functionality to post content to recipient sites

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_view_display.node.basic_page.default.yml
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_view_display.node.basic_page.teaser.yml
ecms_base/features/custom/ecms_basic_page/config/install/field.field.node.basic_page.field_basic_page_paragraphs.yml
ecms_base/features/custom/ecms_basic_page/config/install/field.storage.node.field_basic_page_paragraphs.yml
ecms_base/features/custom/ecms_basic_page/ecms_basic_page.info.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.formatted_text.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.formatted_text.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/editor.editor.paragraph_text.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.formatted_text.field_text.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_text.yml
ecms_base/features/custom/ecms_paragraphs/config/install/filter.format.paragraph_text.yml
ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.formatted_text.yml
ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.features.yml
ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.info.yml

Adds a new feature 'ecms_paragraphs'
Adds a new text format used by new "Formatted Text" paragraph type
Installs paragraphs and new paragraph type by default
Adds the allowed_formats module to restrict format options (installed by default)
Updates basic page to add a paragraph reference field
There are some workflow / content moderation settings that have been introduced into the basic page feature. We had previously been removing these, but I feel that during this development phase we should leave them in, as it's tedious to remove these manually, and I think we're going to be faced with that for a while until development stabilizes. Since this is a default content type, assigned to the default workflow, the risk is very low so for now I think we can keep this as is. 
| Question | Answer …

Add base paragraph feature, update basic page content type

---

CHANGELOG.md
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.media.executive_order_pdf.changed.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.media.executive_order_pdf.created.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.media.executive_order_pdf.path.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.media.executive_order_pdf.status.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.media.executive_order_pdf.uid.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.node.executive_order.changed.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.node.executive_order.created.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.node.executive_order.sticky.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.base_field_override.node.executive_order.uid.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_form_display.media.executive_order_pdf.default.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_form_display.media.executive_order_pdf.media_library.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_form_display.node.executive_order.default.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.media.executive_order_pdf.default.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.media.executive_order_pdf.media_library.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.node.executive_order.default.yml
ecms_base/features/custom/ecms_executive_orders/config/install/core.entity_view_display.node.executive_order.teaser.yml
ecms_base/features/custom/ecms_executive_orders/config/install/field.field.node.executive_order.field_executive_order_long_title.yml
ecms_base/features/custom/ecms_executive_orders/config/install/field.field.node.executive_order.field_executive_order_text.yml
ecms_base/features/custom/ecms_executive_orders/config/install/language.content_settings.media.executive_order_pdf.yml
ecms_base/features/custom/ecms_executive_orders/config/install/language.content_settings.node.executive_order.yml
ecms_base/features/custom/ecms_executive_orders/config/install/rabbit_hole.behavior_settings.node_type_executive_order.yml
ecms_base/features/custom/ecms_executive_orders/ecms_executive_orders.info.yml
ecms_base/features/custom/ecms_executive_orders/tests/src/ExistingSite/EcmsExecutiveOrdersInstallTest.php

This adds translation support to the executive order content type.
| Relevant links | [RIG-84](https://thinkoomph.jira.com/browse/rig-84)

Add translation support to the executive order content type

---

CHANGELOG.md
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.media.publication_file.changed.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.media.publication_file.created.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.media.publication_file.path.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.media.publication_file.status.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.media.publication_file.uid.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.node.publication.changed.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.node.publication.created.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.node.publication.sticky.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.node.publication.uid.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publications_list.created.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.paragraph.publications_list.status.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.taxonomy_term.publication_audience.changed.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.taxonomy_term.publication_topic.changed.yml
ecms_base/features/custom/ecms_publications/config/install/core.base_field_override.taxonomy_term.publication_type.changed.yml
ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.media.publication_file.default.yml
ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.media.publication_file.media_library.yml
ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.node.publication.default.yml
ecms_base/features/custom/ecms_publications/config/install/core.entity_form_display.paragraph.publications_list.default.yml
ecms_base/features/custom/ecms_publications/config/install/field.field.node.publication.field_publication_url.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.media.publication_file.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.node.publication.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.paragraph.publications_list.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.taxonomy_term.publication_audience.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.taxonomy_term.publication_topic.yml
ecms_base/features/custom/ecms_publications/config/install/language.content_settings.taxonomy_term.publication_type.yml
ecms_base/features/custom/ecms_publications/ecms_publications.info.yml
ecms_base/features/custom/ecms_publications/tests/src/ExistingSite/EcmsPublicationsInstallTest.php

This adds translation support for the publication content type and the supporting media/taxonomy/paragraph included in the feature.
| Unit/Functional tests reflect changes? | yes (mostly)
| Relevant links | [RIG-87](https://thinkoomph.jira.com/browse/rig-87)

Add translation support to the publication content feature

---

CHANGELOG.md
ecms_base/features/custom/ecms_speeches/config/install/core.base_field_override.node.speech.changed.yml
ecms_base/features/custom/ecms_speeches/config/install/core.base_field_override.node.speech.created.yml
ecms_base/features/custom/ecms_speeches/config/install/core.base_field_override.node.speech.sticky.yml
ecms_base/features/custom/ecms_speeches/config/install/core.base_field_override.node.speech.uid.yml
ecms_base/features/custom/ecms_speeches/config/install/core.entity_form_display.node.speech.default.yml
ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.default.yml
ecms_base/features/custom/ecms_speeches/config/install/core.entity_view_display.node.speech.teaser.yml
ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_long_title.yml
ecms_base/features/custom/ecms_speeches/config/install/field.field.node.speech.field_speech_text.yml
ecms_base/features/custom/ecms_speeches/config/install/language.content_settings.node.speech.yml
ecms_base/features/custom/ecms_speeches/ecms_speeches.info.yml
ecms_base/features/custom/ecms_speeches/tests/src/ExistingSite/EcmsSpeechesInstallTest.php

This updates the ecms_speeches feature to include translation support for the content type and fields.
| Relevant links | [RIG-88](https://thinkoomph.jira.com/browse/rig-88)

Add translation support to the speeches content type

---

CHANGELOG.md
composer.json
ecms_base/modules/custom/ecms_api/src/EcmsApiBase.php
ecms_base/modules/custom/ecms_api/tests/src/Unit/EcmsApiBaseTest.php
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.module
ecms_base/modules/custom/ecms_api_recipient/config/install/user.role.ecms_api_recipient.yml
ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/ExistingSite/InstallationTest.php
ecms_base/modules/custom/ecms_api_recipient/tests/src/Unit/Form/EcmsApiRecipientConfigFormTest.php

This updates the permissions for syndicated content to be posted in different translations. A core patch was required to get [translation support working with JsonAPI](https://www.drupal.org/project/drupal/issues/2794431#comment-13841477), as that is not currently supported. This also converted the original Functional test to an ExistingSite test. …

Fix the language syndication for the Ecms API

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.node.landing_page.full.yml
ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml

This PR add the Layout Builder Restrictions module and configures the Landing page content type with what blocks can be placed.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-37

Add Layout Builder Restrictions and configure Landing Page

---

CHANGELOG.md
docs/authentication.md
ecms_base/config/install/user.role.drupal_admin.yml
ecms_base/ecms_base.post_update.php
ecms_base/modules/custom/ecms_authentication/src/EcmsUserAuthentication.php
ecms_base/modules/custom/ecms_authentication/tests/src/Unit/EcmsUserAuthenticationTest.php

This updates the admin group name to 'Drupal_Admin'.
| Relevant links | [RIG-121](https://thinkoomph.jira.com/browse/rig-121)

Updated the AAD admin group name

---

CHANGELOG.md
ecms_base/config/install/scheduler.settings.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install
ecms_base/ecms_base.profile
ecms_base/features/custom/ecms_basic_page/ecms_basic_page.info.yml
ecms_base/features/custom/ecms_event/ecms_event.info.yml
ecms_base/features/custom/ecms_executive_orders/ecms_executive_orders.info.yml
ecms_base/features/custom/ecms_hotel/ecms_hotel.info.yml
ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml
ecms_base/features/custom/ecms_location/ecms_location.info.yml
ecms_base/features/custom/ecms_person/ecms_person.info.yml
ecms_base/features/custom/ecms_press_release/ecms_press_release.info.yml
ecms_base/features/custom/ecms_projects/ecms_projects.info.yml
ecms_base/features/custom/ecms_promotions/ecms_promotions.info.yml
ecms_base/features/custom/ecms_publications/ecms_publications.info.yml
ecms_base/features/custom/ecms_speeches/ecms_speeches.info.yml
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php

Add the scheduler module by default with automatic assignment for new content types. Using the existing workflow service to accomplish this since this needs to happen for all new content types (except notifications).
Adds the scheduler module as a dependency for all applicable content types (features).
Enables dblog by default for now.
Removes the workflow assignment loop from the .install hook, since this is happening via the bundle_insert hook so we were running it twice. Also, due to a code error, the notification content type was previously being assigned to the workflow with other content types, which we don't want.
Updates the update_9001 hook to add the workflow assignment so existing sites will receive the scheduler work. This includes installation of the scheduler module in said …

Add the scheduler module and config

---

CHANGELOG.md
docs/authentication.md
ecms_base/config/install/openid_connect.settings.windows_aad.yml
ecms_base/ecms_base.post_update.php
ecms_base/modules/custom/ecms_authentication/ecms_authentication.module
ecms_base/modules/custom/ecms_authentication/src/EcmsUserAuthentication.php
ecms_base/modules/custom/ecms_authentication/tests/src/Unit/EcmsUserAuthenticationTest.php
phpunit.xml

Active directory settings were setup as strict, which was removing manually applied roles upon login. This fixes the login to leave manually applied roles alone _except_ for the Drupal_Admin, which is the only group that should be maintained within AAD. 
| Relevant links | [RIG-136](https://thinkoomph.jira.com/browse/rig-136)

Fix the Active Directory strict role mapping

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.libraries.yml
ecms_base/themes/custom/ecms/templates/layout/layout--four-column.html.twig
ecms_base/themes/custom/ecms/templates/layout/layout--one-column.html.twig
ecms_base/themes/custom/ecms/templates/layout/layout--three-column.html.twig
ecms_base/themes/custom/ecms/templates/layout/layout--two-column.html.twig

This is a small PR that removes jQuery and updates some twig template locations in PL.
| Did you apply meaningful labels to the pull request? | yes/
| Relevant links | https://thinkoomph.jira.com/browse/RIG-67

Remove jQuery from eCMS and change layout templates locations

---

CHANGELOG.md
ecms_base/config/install/system.menu.social-navigation.yml
ecms_base/ecms_base.profile
ecms_base/modules/custom/ecms_distribution/README.md
ecms_base/modules/custom/ecms_distribution/ecms_distribution.module

This adds a new `social-navigation` menu to the profile and provides the update hook to install it to the existing sites.
Additional form_alter logic was added to the ecms_distribution module that will alter the menu link form for the social navigation menu and will provide a predefined list of social media icons that the patternlab theme provides. This information is then added to the menu links as class/title attributes that can be passed into pattern lab twig files.
| Unit/Functional tests reflect changes? | …

Social navigation form alterations

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_recipient/ecms_api_recipient.services.yml

The live site was throwing a php error during cron that pointed back to a misnamed class in the services file. The case of the class name was incorrect. This fixes that case issue and should resolve the issue.
| Relevant links | [RIG-143](https://thinkoomph.jira.com/browserig-143)

Fixed the class path

---

CHANGELOG.md
composer.json
ecms_base/config/install/language.negotiation.yml
ecms_base/config/install/language.types.yml
ecms_base/config/install/language_cookie.negotiation.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.profile
ecms_base/modules/custom/ecms_languages/README.md
ecms_base/modules/custom/ecms_languages/ecms_languages.module
ecms_base/modules/custom/ecms_languages/src/LanguageNegotiationSessionFix.php
ecms_base/modules/custom/ecms_languages/tests/src/Unit/LanguageNegotiationSessionFixTest.php

This adds the language_cookie module and adds a custom language negotiator to properly handle session/cookie within the admin pages.
| Relevant links | [RIG-148](https://thinkoomph.jira.com/browse/rig-148)

Fix language detection to use cookies/sessions instead of URL.

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_publisher/tests/src/Functional/PublisherInstallTest.php
ecms_base/modules/custom/ecms_languages/src/LanguageNegotiationSessionFix.php
ecms_base/modules/custom/ecms_languages/tests/src/Unit/LanguageNegotiationSessionFixTest.php

This removes the node specific restrictions to allow the session/cookie language detection to work with all entities.
| Relevant links | [RIG-149](https://thinkoomph.jira.com/browse/rig-149)

Fix session language detection for all entities.

---

CHANGELOG.md
ecms_base/modules/custom/ecms_languages/src/LanguageNegotiationSessionFix.php
ecms_base/modules/custom/ecms_languages/tests/src/Unit/LanguageNegotiationSessionFixTest.php

This fixes the appended `?language=` to entity view links and forces it to only apply to entity form routes.
| Relevant links | [RIG-153](https://thinkoomph.jira.com/browse/rig-153)

Fix the language interface detection to only apply to entity forms.

---

CHANGELOG.md
composer.json
ecms_base/modules/custom/ecms_languages/ecms_languages.info.yml
ecms_base/modules/custom/ecms_languages/ecms_languages.install
ecms_base/modules/custom/ecms_languages/ecms_languages.module

This adds the drupal/language_neutral_aliases module to force all url aliases to be language neutral. This also adds pathauto hooks to force all auto-generated paths to be language neutral. Finally, an update hook was added to convert all existing paths to be language neutral [per the recommendation of the language_neutral_aliases module](https://git.drupalcode.org/project/language_neutral_aliases/-/blob/3.x/README.txt)
| Risk …

Change path aliases to be language neutral

---

CHANGELOG.md
composer.json
ecms_base/modules/custom/ecms_migration/README.md
ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.migrations.yml
ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.settings.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page_url.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file_media.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file_redirect.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration_group.ecms.yml
ecms_base/modules/custom/ecms_migration/config/schema/ecms_migration.schema.yml
ecms_base/modules/custom/ecms_migration/ecms_migration.info.yml
ecms_base/modules/custom/ecms_migration/ecms_migration.links.action.yml
ecms_base/modules/custom/ecms_migration/ecms_migration.links.menu.yml
ecms_base/modules/custom/ecms_migration/ecms_migration.module
ecms_base/modules/custom/ecms_migration/ecms_migration.routing.yml
ecms_base/modules/custom/ecms_migration/src/Form/EcmsMigrationConfigForm.php
ecms_base/modules/custom/ecms_migration/tests/src/Unit/Form/EcmsMigrationConfigFormTest.php
scripts/ci-develop.sh
scripts/develop.sh

This adds a new ecms_migration module that will take a google sheet of urls and create basic pages and file/media entities from those URLS.
| Unit/Functional tests reflect changes? | yes (mostly)
| Relevant links | [RIG-106](https://thinkoomph.jira.com/browse/rig-106)

Add basic page and file migrations

---

CHANGELOG.md
ecms_base/config/install/user.role.anonymous.yml
ecms_base/features/custom/ecms_landing_page/config/install/block_content.type.content_components.yml
ecms_base/features/custom/ecms_landing_page/config/install/block_content.type.page_title_with_photo.yml
ecms_base/features/custom/ecms_landing_page/config/install/block_content.type.text_card_collection.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.block_content.page_title_with_photo.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.block_content.text_card_collection.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.page_title_with_photo.field_image.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.text_card_collection.field_cards.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.text_card_collection.field_collection_card_style.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.text_card_collection.field_collection_description.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_cards.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_collection_card_style.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_collection_description.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_image.yml
ecms_base/features/custom/ecms_landing_page/config/install/language.content_settings.block_content.text_card_collection.yml
ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.paragraph.text_card.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.paragraph.text_card.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.text_card.field_card_title.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.field.paragraph.text_card.field_text.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.paragraph.field_card_title.yml
ecms_base/features/custom/ecms_paragraphs/config/install/paragraphs.paragraphs_type.text_card.yml
ecms_base/modules/custom/ecms_blocks/src/Form/SearchBlockForm.php
ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--page-title-with-photo.html.twig
ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--text-card-collection.html.twig
ecms_base/themes/custom/ecms/templates/fields/field--field-collection-description.html.twig
ecms_base/themes/custom/ecms/templates/fields/field--paragraph--field-text--text-card.html.twig
ecms_base/themes/custom/ecms/templates/paragraphs/paragraph--text-card.html.twig

This PR adds:
- Text Card paragraph bundle. 
- Text Card Collection block type.
- Page title with photo block type.
These were added to ecms_paragraphs and  ecms_landing_page respectively.
| Risk level | Low, 
| Relevant links | https://thinkoomph.jira.com/browse/RIG-131

Add Text Card Collection and Page Title with Photo

---

CHANGELOG.md
composer.json

Running the ecms_migration with Drush on Acquia was throwing function not defined errors. This adds a patch to fix those errors.
| Relevant links | [RIG-106](https://thinkoomph.jira.com/browse/rig-106)

Fix to allow drush to run migration tools migrations

---

CHANGELOG.md
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.content_components.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.page_title_with_photo.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_form_display.block_content.text_card_collection.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/core.entity_view_display.block_content.content_components.default.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.field.block_content.content_components.field_components_bg_color.yml
ecms_base/features/custom/ecms_landing_page/config/install/field.storage.block_content.field_components_bg_color.yml
ecms_base/features/custom/ecms_landing_page/ecms_landing_page.info.yml
ecms_base/features/custom/ecms_promotions/config/install/block_content.type.promotion_reference.yml
ecms_base/features/custom/ecms_promotions/config/install/core.entity_form_display.block_content.promotion_reference.default.yml
ecms_base/features/custom/ecms_promotions/config/install/core.entity_view_display.block_content.promotion_reference.default.yml
ecms_base/features/custom/ecms_promotions/config/install/field.field.block_content.promotion_reference.field_promotions.yml
ecms_base/features/custom/ecms_promotions/config/install/field.storage.block_content.field_promotions.yml
ecms_base/features/custom/ecms_promotions/config/install/language.content_settings.block_content.promotion_reference.yml
ecms_base/features/custom/ecms_promotions/config/install/language.content_settings.paragraph.promotion_reference.yml
ecms_base/features/custom/ecms_promotions/ecms_promotions.info.yml
ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--content-components.html.twig
ecms_base/themes/custom/ecms/templates/fields/field--block-content--field-promotions.html.twig

This PR:
- includes the new block type: promo reference
- Adds background color field to content components
- Adds in the missing form settings for the block types added previously

Promo reference block type, content components bg color, missing form settings

---

CHANGELOG.md
ecms_base/features/custom/ecms_publications/config/install/views.view.publications.yml
ecms_base/features/custom/ecms_publications/ecms_publications.info.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/README.md
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_subtypes.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_types.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration_group.ecms_covid_publications.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/ecms_covid_publication_migrate.info.yml
ecms_base/modules/custom/ecms_migration/README.md
ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.migrations.yml
ecms_base/modules/custom/ecms_migration/config/install/ecms_migration.settings.yml
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_publications.yml
ecms_base/modules/custom/ecms_migration/config/schema/ecms_migration.schema.yml
scripts/develop.sh

This PR adds a new `ecms_covid_publication_migrate` module that is specific to the Covid site. This module sets up a migration that pulls data from an RSS feed and creates publication nodes and the associated taxonomy terms for the nodes.
This also adds a Google Sheet migration to the ecms_migration module to allow for other sites to migrate in publications if necessary.
The `ecms_publications` feature also added a new publications view that will collect all of the publications and display them in a table with an exposed filter on the type and language. …

Publication node migrations

---

CHANGELOG.md
composer.json
ecms_base/config/install/user.role.site_admin.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.profile

This adds the role_delegation module and configures it to allow the site admin role to assign the content author and content publisher roles. No other roles can be assigned by the site admin.
| Relevant links | [RIG-163](https://thinkoomph.jira.com/browse/rig-163)

Site admin role permissions

---

.gitignore
CHANGELOG.md
ecms_base/config/install/system.theme.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.profile
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_breadcrumbs.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_content.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_help.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_local_actions.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_messages.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_page_title.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_primary_local_tasks.yml
ecms_base/themes/custom/ecms_claro/config/optional/block.block.ecms_claro_secondary_local_tasks.yml
ecms_base/themes/custom/ecms_claro/css/style.css
ecms_base/themes/custom/ecms_claro/ecms_claro.info.yml
ecms_base/themes/custom/ecms_claro/ecms_claro.libraries.yml

This adds a new `ecms_claro` administration theme to the profile and sets it as the default for the profile. The css was allowed to be committed as SASS is not going to be used in this theme.
| Relevant links | [RIG-166](https://thinkoomph.jira.com/browse/rig-166)

Add an admin sub-theme of Claro for eCMS customizations

---

CHANGELOG.md
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publication_types.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/config/install/migrate_plus.migration.ecms_covid_publications_rss.yml
ecms_base/modules/custom/ecms_covid_publication_migrate/ecms_covid_publication_migrate.install

This adds the audience tags to the publications during import. A hook_update function was included to add the new sourceid2 column to the migrate map tables and to import the new configuration.
| Relevant links | [RIG-169](https://thinkoomph.jira.com/browse/rig-169)

Add audience tags to the Covid publication import

---

CHANGELOG.md
composer.json

This patches core to allow layout builder inline blocks to display the contextual links, thus allowing for translation of the inline blocks.
| Relevant links | [RIG-160](https://thinkoomph.jira.com/browse/rig-160)

Add the missing contextual links for Layout Builder blocks

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.links.action.yml
ecms_base/modules/custom/ecms_api_publisher/ecms_api_publisher.links.menu.yml

This adds a new menu link and new actions links to allow administrators to register new syndicated sites.
| Relevant links | [RIG-175](https://thinkoomph.jira.com/browse/rig-175)

Add menu links to create new syndicated sites in a hub.

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/themes/custom/ecms/config/install/ecms.settings.yml
ecms_base/themes/custom/ecms/config/schema/ecms.schema.yml
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/theme-settings.php

This adds the missing `ecms.schema.yml` which is required in order to translate the theme settings.
Also, while working on the translation, I discovered an XSS issue with the way the theme settings were being output. I fixed these to properly sanitize the output of the settings in the preprocess hook.
| Relevant links | [RIG-180](https://thinkoomph.jira.com/browse/rig-180)

Add the missing theme schema to allow translation

---

CHANGELOG.md
ecms_base/config/install/user.role.content_author.yml
ecms_base/config/install/user.role.site_admin.yml
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install

This updates the site_admin role to have the 'interface translation' permission. This also updates the content_author role to have the 'view all revisions' permission. Also, the 9032 hook was renamed to 9033 to reflect the next tag that it will run with.
| Relevant links | [RIG-184](https://thinkoomph.jira.com/browse/rig-184), [RIG-181](https://thinkoomph.jira.com/browse/rig-181)

Add interface translation permission

---

CHANGELOG.md
ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig

This PR fixes the url value of search result teasers. Screenshot shows correct url at bottom:

Fixed url value of search result teasers

---

CHANGELOG.md
ecms_base/themes/custom/ecms/templates/views/views-view-fields--site-search.html.twig

This PR updates the number_format twig function to not include commas which was throwing an error with the path function.

Resolve commas breaking search teaser paths

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_notification_publisher/src/NotificationPublisher.php
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisher.php
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiSyndicate.php
ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
ecms_base/modules/custom/ecms_api_publisher/src/Plugin/QueueWorker/EcmsApiSyndicateQueueWorker.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiPublisherTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/EcmsApiSyndicateTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Plugin/QueueWorker/EcmsApiSyndicateQueueWorkerTest.php
phpunit.xml

This refactors the ecms_api_publisher to handle multiple entity references which will allow any content type to be be syndicated to other sites regardless of the entity references currently for the content type.
| Risk level | Mediua
| Relevant links | [RIG-176](https://thinkoomph.jira.com/browse/rig-176)

Refactor the ecms_api_publisher module to handle entity references

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api/src/EcmsApiBase.php
ecms_base/modules/custom/ecms_api_publication_publisher/README.md
ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.info.yml
ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.module
ecms_base/modules/custom/ecms_api_publication_publisher/ecms_api_publication_publisher.services.yml
ecms_base/modules/custom/ecms_api_publication_publisher/src/PublicationPublisher.php
ecms_base/modules/custom/ecms_api_publication_publisher/tests/src/Unit/PublicationPublisherTest.php
ecms_base/modules/custom/ecms_api_publisher/README.md
ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
ecms_base/modules/custom/ecms_api_publisher/tests/src/Unit/Form/EcmsApiBatchSendUpdateFormTest.php

This adds a module to allow the publication node to be syndicated to other sites. The manual batch form was updated to work with the changes introduced in #177.
| Relevant links | [RIG-177](https://thinkoomph.jira.com/browse/rig-177)

Allow publication nodes to be syndicated to other sites.

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme

The cache contexts for the publication paragraph list wasn't set, causing the audience query parameter to get cached improperly, rendering it ineffective.
| Relevant links | [RIG-200](https://thinkoomph.jira.com/browse/rig-200)

Added the missing cache context for publications

---

.github/workflows/develop.yml
CHANGELOG.md

Adds a github action and associated config that supports PHP setup for the CI workflow. Locks PHP at 7.3 to mimic the target environments.
| Relevant links | https://github.com/shivammathur/setup-php
https://stackoverflow.com/questions/57965588/how-to-test-with-different-versions-of-php-in-a-github-action

Lock PHP version for CI workflows

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SiteNotificationsBlock.php
ecms_base/themes/custom/ecms/config/optional/block.block.sitenotifications.yml
ecms_base/themes/custom/ecms/templates/blocks/block--sitenotifications.html.twig

This PR adds logic to use the current node's langcode for displaying notifications

Add logic to use node's langcode for displaying notifications

---

CHANGELOG.md
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_basic_page.yml

The eohhs migration was showing some missing title SQL errors during import. This adds an h3 search and a default value to the migration which will fix those.
| Relevant links | [RIG-192](https://thinkoomph.jira.com/browse/rig-192)

Added an h3 to the title search and a default value for the title

---

CHANGELOG.md
ecms_base/features/custom/ecms_paragraphs/config/install/core.base_field_override.paragraph.card.created.yml
ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.paragraph.card.yml

The 'Card' paragraph component was not translatable, causing the media items to not show the translated versions.
| Relevant links | [RIG-207](https://thinkoomph.jira.com/browse/rig-207)

Allow the 'Card' paragraph to be translatable

---

CHANGELOG.md
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.media_library.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.media_library.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.field.media.file.field_file_link_behavior.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.media.field_file_link_behavior.yml
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/content/media--file.html.twig

This PR adds a field to file entities that allows content editors to select the link behavior. Either "Download file" or "Open in new tab".
It also resolves an issue that files were not displaying correctly in the media library.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-125

Add media file link behavior field and fix media library display

---

CHANGELOG.md
composer.json
ecms_base/themes/custom/ecms/ecms.theme

This PR adds a patch to fix "Call to a member function getEntityTypeId() on null (Layout Builder)". It also updated the preprocess_block to check if block content exists before accessing the label
| Relevant links | https://thinkoomph.jira.com/browse/RIG-217

Fix "Call to a member function getEntityTypeId() on null (Layout Builder)"

---

CHANGELOG.md
ecms_base/modules/custom/ecms_migration/config/install/migrate_plus.migration.ecms_file_redirect.yml
ecms_base/modules/custom/ecms_migration/ecms_migration.module

During testing of the EOHHS site, 2 things were noticed:
1. Public file path was not set / available in prepareRow call
2. The redirect destination file name was not being encoded, while the imported file name was, causing 404s for files with encoded values.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-233

Update files redirect migration

---

CHANGELOG.md
ecms_base/themes/custom/ecms/templates/views/views-view--press-releases--page_1.html.twig
ecms_base/themes/custom/ecms/templates/views/views-view-unformatted--site-search.html.twig

This PR fixes an issue where press release view was blank after resolving the search view throwing warnings re: row content.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-242

Add row loop variable to both instances of article listing.

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/theme-settings.php

This PR adds a logo only theme setting. This will be used for the OHA site and any site that has a large logo.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-239

Add logo only theme setting

---

CHANGELOG.md
ecms_base/config/install/editor.editor.minimal.yml
ecms_base/config/install/user.role.authenticated.yml
ecms_base/features/custom/ecms_notification/config/install/core.entity_form_display.node.notification.default.yml
ecms_base/features/custom/ecms_notification/config/install/core.entity_view_display.node.notification.default.yml
ecms_base/features/custom/ecms_notification/config/install/core.entity_view_display.node.notification.teaser.yml
ecms_base/features/custom/ecms_notification/config/install/field.field.node.notification.field_notification_weight.yml
ecms_base/features/custom/ecms_notification/config/install/field.storage.node.field_notification_weight.yml
ecms_base/features/custom/ecms_notification/ecms_notification.module
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SiteNotificationsBlock.php

This PR is primarily centered around notifications. 
- A new field was added that lets content editors set a weight to a notification which will control where it appears in the list.
- The notification block was updated to only fetch notifications that haven't expired.
- A hook_cron was added to unpublish notifications that are expired. 
Also included is some small config changes that were missed in the last deployment. All 3 of the sites have had these changes manually done on production so a hook_update is not required.
| Did you perform browser …

Notification weighting and expiration functionality

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
ecms_base/features/custom/ecms_event/config/install/core.entity_form_display.node.event.default.yml
ecms_base/features/custom/ecms_event/config/install/core.entity_view_display.node.event.default.yml
ecms_base/features/custom/ecms_event/config/install/core.entity_view_display.node.event.teaser.yml
ecms_base/features/custom/ecms_event/config/install/feeds.feed_type.ical_feed.yml
ecms_base/features/custom/ecms_event/config/install/field.field.node.event.feeds_item.yml
ecms_base/features/custom/ecms_event/config/install/field.storage.node.feeds_item.yml
ecms_base/features/custom/ecms_event/ecms_event.info.yml
ecms_base/modules/custom/ecms_feeds/ecms_feeds.info.yml
ecms_base/modules/custom/ecms_feeds/src/Feeds/Item/EcmsIcalItem.php
ecms_base/modules/custom/ecms_feeds/src/Feeds/Parser/EcmsIcalParser.php

This PR adds a custom iCal parser included in a custom module ecms_feeds. This also includes the necessary config to add the feed type to existing ecms_event feature package.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-251

iCal feeds config, parser, and item

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install

This PR fixes a missing module dependency from 0.4.8 release.

Fixed missing module dependency media_library_form_element

---

CHANGELOG.md
composer.json
ecms_base/themes/custom/ecms/ecms.info.yml
ecms_base/themes/custom/ecms/templates/blocks/block--google-translator.html.twig

This PR pulls in the google translator module and themes it. It will not be enabled by default and will be enabled on a site by site basis.
| Relevant links | https://thinkoomph.jira.com/browse/RIG-266

Add google translator module

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/layout/html.html.twig

This PR moves the palette class to the HTML tag rather than the body.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-52

Move palette class to HTML tag

---

CHANGELOG.md
composer.json
ecms_base/features/custom/ecms_event/config/install/views.view.events.yml
ecms_base/features/custom/ecms_event/ecms_event.info.yml
ecms_base/themes/custom/ecms/templates/content/node--event--full.html.twig
ecms_base/themes/custom/ecms/templates/content/node--event--teaser.html.twig

This PR handles several small changes to the event functionality site that span multiple tickets.
- RIGA-62: Support events that span multiple months in teaser view.
- RIGA-62: Added patch for smart_date to fix issue with all day dates.
- RIGA-61: Changed events view to use end date rather than start date for filter.
- RIGA-63: Fixed frontend output for all day events.
- RIGA-77: Fixed events not showing registration url.
| Did you apply meaningful labels to the pull request? | ye
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-62, …

Several small event updates

---

CHANGELOG.md
ecms_base/themes/custom/ecms/templates/content/node--event--teaser.html.twig

Fixed issue with events displaying incorrect month. Start value was always returning the value of the current month rather than pulling from field.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-85

Fixed issue with events displaying incorrect month.

---

CHANGELOG.md
ecms_base/ecms_base.install

Fixed missing file icons by adding hook_install to copy files.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-89

Fix missing file icon in media library

---

CHANGELOG.md
composer.json
ecms_base/modules/custom/ecms_languages/ecms_languages.module

This updates the publishcontent module which provides the publishing toggle tabs we want to target and remove.
It removes a patch that was committed to the recent release (yay @pfrilling !).
The logic is provided via the menu_local_tasks_alter hook
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-21

Remove unpublish and publish tabs from node

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.info.yml
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/layout/page--landing-page.html.twig
ecms_base/themes/custom/ecms/templates/layout/page.html.twig
ecms_base/themes/custom/ecms/theme-settings.php
scripts/develop.sh

This PR adds a theme setting to pick an illustration and pass it to patternlab.
Also included is the necessary change to lock Drupal core.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-74

Setup profile to handle illustrations

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.install

Updates the search dependencies, removes old acquia search solr module.
Adds the Acquia Search dependency.
This goes with ecms_distribution PR https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/pull/114
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-98

Search module updates

---

CHANGELOG.md
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.media.file.media_library.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_form_display.taxonomy_term.file_tags.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.default.yml
ecms_base/features/custom/ecms_paragraphs/config/install/core.entity_view_display.media.file.media_library.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.field.media.file.field_file_tags.yml
ecms_base/features/custom/ecms_paragraphs/config/install/field.storage.media.field_file_tags.yml
ecms_base/features/custom/ecms_paragraphs/config/install/language.content_settings.taxonomy_term.file_tags.yml
ecms_base/features/custom/ecms_paragraphs/config/install/rabbit_hole.behavior_settings.taxonomy_vocabulary_file_tags.yml
ecms_base/features/custom/ecms_paragraphs/config/install/taxonomy.vocabulary.file_tags.yml
ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.features.yml
ecms_base/features/custom/ecms_paragraphs/ecms_paragraphs.info.yml

Adds a new vocabulary "File Tags" and associated term reference field to the media file bundle.
Optional field, single term only.
Terms are translatable.
Added to the ecms_paragraphs feature which contains the media file bundle.
This is the next step in the larger file list by taxonomy component. This will allow client to begin file tagging on development sites while we work to finish the actual paragraph component that will be used to output files by a given term.
| …

Add taxonomy for media files

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/views/views-view-unformatted--acquia-search.html.twig

This PR references a new Pattern Lab component for a search state CTA. The component will redirect users to the ri.gov site search.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-162

Add Search State CTA to acquia search results

---

CHANGELOG.md
ecms_base/modules/custom/ecms_blocks/src/Form/SearchStateBlockForm.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SearchStateBlock.php
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/blocks/block--ecms-search-state-block.html.twig

This PR adds a search state block that can be used instead of the existing search block. The search link is hardcoded as discussed previously. This will be a manual process of switching blocks for the sites that would like to use it.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-163

Add search state block

---

CHANGELOG.md
composer.json

Attempting to update core to 9.2.9 and the patch for issue was committed.
There is discussion after commit about a break/bug that as of now is unresolved but not sure if it impacts us or not.
To test, check out this feature branch from ecms_distribution and review locally:
https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/tree/RIGA-167/sa-core-011
| Risk level |, Medium, …

Remove committed patch from 3020876

---

.github/pull_request_template.md
CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_workflow/README.md
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
scripts/ci-develop.sh

Add a "removefromworkflow" method to the ecmsWorkflow class so there is a way to programmatically remove a content type from the existing workflow. Add press release to the exclude list so it's not added to future sites.
Write update hook to call the new remove method.
Update PR template per our new specs.
Added a ecms_workflow readme file.
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-185

Riga 185/remove press from workflow

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/templates/blocks/block--inline-block--content-components.html.twig

Add block translate links for each inline block component. Only adds them to translated nodes. This temporarily resolves the issue in RIGA-182 where admins no longer get the contextual links on inline block for layout builder enabled pages.
Checkout branch and review locally, ensure links are shown for authenticated users but not for anonymous.
Add a new landing page with no translation, add a block. Should not see translate link.
Logged in, translated node:
Logged out, translated node:
Logged in, untranslated node:
| Documentation reflects changes? | y - comments should be helpful when we remove this.
| Did …

Add translation link to inline blocks

---

CHANGELOG.md
ecms_base/modules/custom/ecms_blocks/src/Form/SearchBlockForm.php
ecms_base/modules/custom/ecms_blocks/src/Form/SearchStateBlockForm.php

This PR fixes an accessibility issue with the aria-label missing from search block input.
Test the search block in the header to see if it has an aria-label.
| Risk level | l 
| Relevant links | https://thinkoomph.jira.com/browse/RIGA-191

Add aria-label to search block input

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_feeds/src/Feeds/Parser/EcmsIcalParser.php
ecms_base/modules/custom/ecms_workflow/config/install/ecms_workflow.settings.yml
ecms_base/modules/custom/ecms_workflow/ecms_workflow.links.menu.yml
ecms_base/modules/custom/ecms_workflow/ecms_workflow.routing.yml
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
ecms_base/modules/custom/ecms_workflow/src/Form/EcmsWorkflowConfigForm.php

Restore press release to default workflow (remove from class CONST exclude variable, add update hook).
Added config to ecms_workflow to allow sites to exclude content types from workflow.
Fixed PHP fatal error coming from Feeds custom parser.
| Risk level |

Restore press to workflow, provide option to exclude on a site

---

CHANGELOG.md

- RIGA-301: Add increased memory limits and timeouts to .env file.
- RIGA-282: Update drupal/core 9.3.19 => 9.4.5.
- RIGA-282: Update core patch for issue 1356276.
- RIGA-297: Save config for Acquia search view after db update.
- RIGA-301: Comment out functional tests from develop script.

Prepare CHANGELOG for 0.9.12 release

---

CHANGELOG.md
composer.json
ecms_base/modules/custom/ecms_distribution/ecms_distribution.module

- Updates drupal/acsf 2.72 => 2.73
- Fixes a new PHPCS linting error by prepending module name to function.
- `get_patternlab_social_source` => `ecms_distribution_get_patternlab_social_source`
See RIGA-308
| Risk level |M
| Relevant links | [RIGA-308](https://thinkoomph.jira.com/browse/RIGA-308) , [Related distribution PR](https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/pull/182)

September module updates

---

CHANGELOG.md

- RIGA-308: Update drupal/acsf 2.72 => 2.73.

Prepare CHANGELOG for 0.9.13 release

---

CHANGELOG.md

- RIGA-333: Upgrading drupal/paragraphs 1.14.0 => 1.15.0.
- RIGA-333: Upgrading drupal/media_revisions_ui 2.0.0 => 2.1.0.
- RIGA-333: Upgrading drupal/media_library_form_element 2.0.3 => 2.0.4.
- RIGA-333: Upgrading drupal/media_file_delete 1.1.1 => 1.3.0.
- RIGA-333: Upgrading drupal/media_entity_file_replace 1.0.0 => 1.1.0.
- RIGA-333: Upgrading drupal/layout_builder_restrictions 2.13.0 => 2.17.0.
- RIGA-333: Upgrading drupal/acquia_connector 4.0.0 => 4.0.1.
- RIGA-337: Upgrading acquia_connector also fixes fatal error (issue 3316912).

Prepare CHANGELOG for 0.9.19 release

---

CHANGELOG.md

- RIGA-336: Updated allowed formats to 2.x.
- RIGA-336: Added patch for allowed formats issue 2950548.

Prepare CHANGELOG for 0.9.21 release

---

CHANGELOG.md

- RIGA-346: Install drupal/simple_menu_permissions 1.4.0.
- RIGA-346: Install drupal/menu_admin_per_menu 1.5.
- RIGA-346: Add update hook ecms_base_update_9094 to install menu modules.
- RIGA-346: Add update hook ecms_base_update_9095 to update permissions.
- RIGA-346: Update Content Publisher permissions to add Main menu links.
- RIGA-346: Revoke "Use the administration pages" from Content Publishers.

Prepare CHANGELOG for 0.9.22 release

---

CHANGELOG.md

- RIGA-6: Update formatting of library imports for new drupal/components API.
- RIGA-362: Switch from hard-coded to using saved text format value for footer.
- RIGA-364: Update drupal/smart_date version constraint ^3.5 => ^4.0@alpha.
- RIGA-362: Remove Delete content and media Permission from Content Publishers.

Prepare CHANGELOG for 0.9.23 release

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme

In file ecms.theme, there was a misordered variable usage and declaration; the variable `$language` was set at a later point in code, but was attempting to be used before that.
This re-orders the declaration and setting of that variable, so it is available when it needs to be
| Relevant links | [RIGA-365](https://thinkoomph.jira.com/browse/RIGA-365)

Fix undefined variable bug

---

CHANGELOG.md

- RIGA-365: Add custom module to set search config on site by site basis.
- RIGA-365: Add patch for drupal/search_api, issue 3321499, comment #7.
- RIGA-360: Fix disappearing dropdown selector on publications search.
- RIGA-365: Fix undefined variable bug.

Prepare CHANGELOG for 0.9.24 release

---

CHANGELOG.md

- RIGA-371: Update user role permissions, add db update to import config.
- RIGA-372: Install, enable by default, and configure drupal/autologout ^1.4.

Prepare CHANGELOG for 0.9.25 release

---

CHANGELOG.md
composer.json

- Installs `drupal/feeds_ex` ^1.0@beta.
- Installs `softcreatr/jsonpath`, a sub-module for feeds_ex.
- Replaces `querypath/querypath` with `gravitypdf/querypath`.
- The old package is no longer maintained, the new is an actively maintained fork of the original
- New version contains a composer "replace" section; should resolve composer errors for anything that previously relied on querypath.
Go to edit the configuration of a Feed
e.g. `/admin/structure/feeds/manage/olis_delivery_weekly_schedule_20`
In the dropdown selector for Basic Settings -> Parser, verify that JSON options are now available
| Unit/Functional tests …

Install feeds ex module

---

CHANGELOG.md

- RIGA-380: Install drupal/feeds_ex ^1.0@beta.
- RIGA-380: Install softcreatr/jsonpath, a sub-module for feeds_ex.
- RIGA-380: Replace querypath/querypath with gravitypdf/querypath.

Prepare CHANGELOG for 0.9.26 release

---

CHANGELOG.md
ecms_base/modules/custom/ecms_languages/README.md
ecms_base/modules/custom/ecms_languages/ecms_languages.module

Adds hook_form_alter to remove langcodes from views exposed filter dropdown selector, which are included by default but not wanted.
- Removing only these standard values allows different sites to maintain their own different languages
This is in use on the Covid site, on the Publications search page `/publications`
Visit page and make sure these are no longer present:
- Site's Default language
- Interface text language selected for page
- Content language selected for page
- Not Applicable
- Not Specified
| Documentation reflects changes? |Y
| Did you provide detail in the …

Remove languages from dropdown with form hook

---

CHANGELOG.md

- RIGA-344: Add form alter hook to remove langcodes from publications selector.

Prepare CHANGELOG for 0.9.27 release

---

CHANGELOG.md
ecms_base/config/install/autologout.role.ecms_api_recipient.yml
ecms_base/config/install/autologout.role.embed_author.yml
ecms_base/config/install/autologout.role.form_author.yml
ecms_base/ecms_base.install
ecms_base/ecms_base.post_update.php

The `embed_author` role had the necessary permissions to edit paragraphs, but was missing the permission to use the text format.
This adds a post update hook to grant the permission 'use text format embed' to the embed_author role
Also deletes some unneeded config files introduced recently while installing autologout module.
- Visit permissions UI `/admin/people/permissions`
- Search for "Use the Embed text format"
- Verify that the checkbox corresponding to `embed_author` is now checked
| Did you provide detail in the summary on how and …

Fix text format permission for Embed Author role

---

CHANGELOG.md

- RIGA-384: Add post update, fix text format permissions for embed_author.

Prepare CHANGELOG for 0.9.28 release

---

CHANGELOG.md
composer.json

In conjunction with June contrib module updates (distribution PR https://github.com/State-of-Rhode-Island-eCMS/ecms_distribution/pull/238)
This updates the composer version constraint for simple_sitemap to use the 4.x branch now.
| Relevant links | [RIGA-390](https://thinkoomph.jira.com/browse/RIGA-390)

Update drupal/simple_sitemap requirement

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiSiteAccessControlHandler.php
ecms_base/modules/custom/ecms_api_publisher/src/Entity/EcmsApiSite.php
ecms_base/modules/custom/ecms_api_publisher/src/Form/EcmsApiBatchSendUpdatesForm.php
ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiRecipientInstall.php
ecms_base/modules/custom/ecms_api_recipient/src/Form/EcmsApiRecipientConfigForm.php
ecms_base/modules/custom/ecms_blocks/src/Form/SearchStateBlockForm.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/HotelListingBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/PromotionsGlobalBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/PromotionsNodeSpecificBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SearchBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SearchStateBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SidebarContentBlock.php
ecms_base/modules/custom/ecms_blocks/src/Plugin/Block/SiteNotificationsBlock.php
ecms_base/modules/custom/ecms_feeds/src/Feeds/Parser/EcmsIcalParser.php
ecms_base/modules/custom/ecms_icon_library/src/Plugin/Field/FieldFormatter/EcmsIconLibraryFormatter.php
ecms_base/modules/custom/ecms_icon_library/src/Plugin/Field/FieldWidget/EcmsIconLibraryWidget.php
ecms_base/modules/custom/ecms_languages/ecms_languages.module
ecms_base/modules/custom/ecms_layout/ecms_layout.module
ecms_base/modules/custom/ecms_layout/src/Plugin/Layout/LayoutBase.php
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
ecms_base/modules/custom/ecms_workflow/src/Form/EcmsWorkflowConfigForm.php
ecms_base/modules/custom/ecms_workflow/tests/src/ExistingSite/InstallationTest.php
ecms_base/modules/custom/ecms_workflow/tests/src/Unit/EcmsWorkflowBundleCreateTest.php
ecms_base/themes/custom/ecms/ecms.theme

While testing https://thinkoomph.jira.com/browse/RIGA-388, existing files began failing tests.
This is presumably because of a recent change in linting requirements.
This fixes those style/linting errors by alphabetizing all "Use" statements.
Make sure all tests pass during guthub actions
| Relevant links | [RIGA-388](https://thinkoomph.jira.com/browse/RIGA-388)

Alphabetize 'Use' statements to fix codesniffer errors

---

CHANGELOG.md

- RIGA-388: Alphabetize 'Use' statements to fix codesniffer errors.
- RIGA-390: Update drupal/simple_sitemap requirement to ^4.1.

Prepare CHANGELOG for 0.9.29 release

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/modules/custom/ecms_workflow/ecms_workflow.services.yml
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
ecms_base/modules/custom/ecms_workflow/tests/src/Unit/EcmsWorkflowBundleCreateTest.php

- The OLIS site lost the Content Moderation field from its Node edit forms.
- It looks like there were 2 issues: 
- deleted workflow config, 
- and a submit form which adds/removes Node types from the workflow, but which didn't actively do anything to update the node edit forms
- This adds a db update hook to check whether the workflow config exists, and to install it from files if not.
- It also adds to the PHP service related to the form submission, so now the Moderation field is added/removed from form display as appropriate
```
----------- ----------- --------------- ------------------------------------------------------------------------------
Module      Update ID   Type            Description
----------- ----------- --------------- …
```

Fix missing moderation workflow

---

CHANGELOG.md

- RIGA-395: Add 'ecms_base_update_9099' to re-import empty workflow config.
- RIGA-395: Update 'ecms_workflow.bundle_create' to show/hide moderation field.

Prepare CHANGELOG for 0.9.30 release

---

CHANGELOG.md

- RIGA-6: Upgrade to 0.10.0 to reflect drupal/core 9.4.x => 9.5.x upgrade.

Prepare CHANGELOG for 0.10.0 release

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.install
ecms_base/features/custom/ecms_event/config/install/field.field.paragraph.event_list.field_event_list_type.yml

- Updates Event Type field config to be non-required
- `field.field.paragraph.event_list.field_event_list_type.yml`
- Adds update hook `ecms_base_update_9100` to get new field config from the `ecms_event` feature's config directory, and save it to active config
- Check config setting at:
- `/admin/structure/paragraphs_type/event_list/fields/paragraph.event_list.field_event_list_type`
- Make test content:
- Create a node of a type that offers "Event list" in its flex components, e.g. Basic Page; verify you can save a page that does have an "Event List" component added, but that does not have a value for the "Event Type" field
- `/node/add/basic_page` => Add an "Event List" paragraph to the components section.
| Did you apply meaningful labels to …

Update "Event list type" field config to non-required

---

CHANGELOG.md

- RIGA-383: Add ecms_base_update_9100 hook to import updated config.
- RIGA-383: Update the Event List Type field config to be non-required.

Prepare CHANGELOG for 0.10.1 release

---

CHANGELOG.md

- RIGA-406: Update drupal/admin_toolbar 3.4.0 => 3.4.1.
- RIGA-406: Update drupal/easy_breadcrumb ^2.0 => 2.0.5.
- RIGA-406: Update drupal/metatag ^1.14 => ^1.26.
- RIGA-406: Update drupal/token ^1.7 => ^1.12.

Prepare CHANGELOG for 0.10.2 release

---

CHANGELOG.md
ecms_base/modules/custom/ecms_distribution/ecms_distribution.module
ecms_base/themes/custom/ecms/config/schema/ecms.schema.yml
ecms_base/themes/custom/ecms/ecms.theme
ecms_base/themes/custom/ecms/theme-settings.php

There was an existing feature that makes File-type media downloads use the actual directory path of a file, rather than using the Drupal routed media version.
E.g. when this setting is turned on it would use `/sites/default/files/..path/to/file/location../{file_name}` instead of `/media/{ ID }/download`
This sometimes caused a problem when it gave the full and absolute URL (including domain)
This PR updates code to use the relative path (excluding domain) so it will be site-agnostic.
| Did you provide detail in the summary on how and where …

Use transform relative function for file URLs

---

CHANGELOG.md

- RIGA-378: Change from absolute to relative file path for downloadable files.
- RIGA-409: Update drupal/acsf 2.73 => ^2.75.

Prepare CHANGELOG for 0.10.3 release

---

CHANGELOG.md
scripts/develop.sh

To sync with the PHP 8.0 => 8.1 upgrade on Acquia site factory,
this updates version of PHP and Drupal/core for the develop script
| Risk level |M
| Relevant links | [RIGA-414](https://thinkoomph.jira.com/browse/RIGA-414)

Update development scripts to use PHP 8.1

---

CHANGELOG.md

- RIGA-322: Update development scripts to use PHP 8.1.

Prepare CHANGELOG for 0.10.4 release

---

CHANGELOG.md

- RIGA-322: Add hook 'ecms_base_update_9101' to import updated role config.
- RIGA-401: Add hook 'ecms_base_update_9102' to install new modules.
- RIGA-401: Add hook 'ecms_base_update_9103' to import new module config.
- RIGA-401: Add drupal/focal_point ^2.0.1 to composer.json.
- RIGA-401: Add drupal/iek (Image effect kit) ^1.3 to composer.json.
- RIGA-401: Add drupal/entity_usage ^2.0@beta to composer.json.
- RIGA-415: Add drupal/advagg ^6.0@alpha to composer.json.
- RIGA-415: Add drupal/conditional_fields ^4.0@alpha to composer.json.
- RIGA-415: Add drupal/field_group ^3.4 to composer.json.
- RIGA-415: Add drupal/quick_node_clone ^1.16 to composer.json.
- RIGA-322: Update drupal/core-recommended version constraints to also include ^10.0.
- RIGA-322: Include ^10 in …

Prepare CHANGELOG for 0.10.5 release

---

CHANGELOG.md

- RIGA-426: Remove unneeded access check from search response.

Prepare CHANGELOG for 0.10.6 release

---

CHANGELOG.md

- RIGA-6: Temporarily remove code of error-causing hooks.

Prepare CHANGELOG for 0.10.7 release

---

CHANGELOG.md

- RIGA-322: Add google_translator patch 3387636 to resolve HTML render error.
- RIGA-401: Add hook ecms_base_update_9102, enable modules and install config.
- RIGA-431: Add hook ecms_base_update_9103, enable Google Tag for anonymous.

Prepare CHANGELOG for 0.10.8 release

---

CHANGELOG.md
ecms_base/ecms_base.install

Uninstalls Advanced Aggregation, so it is opt-in for site admins instead of enabled by default.
Go to Extend `/admin/modules` and verify Advanced Aggregation is available to be enabled, but is not currently installed/enabled.
AKA verify checkbox is unchecked.
| Risk level |

Add update hook to uninstall drupal/advagg

---

CHANGELOG.md

- RIGA-434: Add ecms_base_update_9104 to uninstall drupal/advagg.
- RIGA-434: Uninstall advagg by default, so it has to be explicitly enabled.

Prepare CHANGELOG for 0.10.9 release

---

CHANGELOG.md

- RIGA-451: Add the Address Phonenumber module to composer.
- RIGA-452: Added the vbo_export module to composer.
- RIGA-448: Added the path redirect import module to the codebase.
- RIGA-446: Drupal 10 upgrade fixes.
[1.0.0]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/0.11.0...1.0.0

Prepare changelog for 1.0.0

---

CHANGELOG.md
ecms_base/modules/custom/ecms_workflow/ecms_workflow.info.yml
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php
scripts/ci-develop.sh
scripts/develop.sh

Permissions were being set too early causing a permission not found error during the bundle create step for nodes.
Create a new content type and confirm no PHP error is thrown.
| Relevant links | [RIGA-458](https://thinkoomph.jira.com/browse/RIGA-458)

RIGA-458/Fixed the workflow permissions order

---

CHANGELOG.md
composer.json

Add a patch to allow paths to be imported.
Enable the module and import a csv file with redirects.
n/a
| Unit/Functional tests cover changes? |n/a
| Relevant links | [RIGA-463](https://thinkoomph.jira.com/browse/RIGA-463)

Riga 463/patch path redirect import

---

CHANGELOG.md

- RIGA-461: Added Drupal Commerce
- RIGA-461: Added Drupal Commerce Stock
- RIGA-461: Added Drupal LinkIt
- RIGA-461: Added Drupal Facets
- RIGA-459: Updated the text formatters and permissions.
- RIGA-458: Fixed the workflow error.
- RIGA-458: Fixed the site installation error.
- RIGA-463: Patched the path redirect import module.
[1.0.1]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.0.0...1.0.1

Prepare changelog for 1.0.1

---

CHANGELOG.md
composer.json
ecms_base/config/install/user.role.site_admin.yml
ecms_base/ecms_base.install

The `site_admin` role had an elevated permission. This revokes that from all new and existing sites.
Install the update and confirm that the `site_admin` no longer has the `administer site configuration` permission.
n/a
| Relevant links | [RIGA-471](https://thinkoomph.jira.com/browse/RIGA-471)

Revoked the site_admin permission

---

CHANGELOG.md

- RIGA-462: Added the disease field to the media migration.
- RIGA-467: Added module to enable plugin for CKEditor column widths
- RIGA-471: Fixed a misconfigured permission.
- RIGA-462: Fixed the configuration dependencies.
[1.0.2]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.0.1...1.0.2

Prepare changelog for 1.0.2

---

CHANGELOG.md
ecms_base/ecms_base.install
ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml

Update the basic page form configuration. Change the Intro Text field to Always show the summary field.
Navigate to /admin/structure/types/manage/basic_page/form-display
The Intro Text field should include `Summary field will always be visible`
| Relevant links | [RIGA-492](https://thinkoomph.jira.com/browse/RIGA-75)

RIGA-492: Change the configuration for the basic page intro text field.

---

CHANGELOG.md
composer.json
ecms_base/themes/custom/ecms/templates/layout/tabs.html.twig

Remove the patch for Layout Builder Tabs and adjust the twig template for tabs to reflect changes that will be part of the newer version of the module. This branch cannot be tested with out a companion PR for the distribution. where the module is updated to 1.0.1. 
- In Layout Builder, verify that the tabs option (for a section) is working as expected.
- View a content item to verify that the tabs are showing as expected.
| …

Remove the Layout Builder Tabs patch

---

ecms_base/ecms_base.install

The update hook in #497 wasn't required and caused database updates to fail during deployment.
- Deploy and confirm that database updates were successful.
- Confirm that the summary option is enabled for basic page intro text.
| `CHANGELOG` reflects changes? |no
| Relevant links | [RIGA-492](https://thinkoomph.jira.com/browse/RIGA-75)

Removed the unnecessary install hook

---

CHANGELOG.md
composer.json

Patches Drupal Core to allow for the WYSIWYG in a views global text area.
Edit a view, add a global text area to a view header and confirm that the WYSIWYG is available.
| Relevant links | [RIGA-488](https://thinkoomph.jira.com/browse/RIGA-488)

Added a patch to allow ckeditor in views global areas

---

CHANGELOG.md
ecms_base/features/custom/ecms_press_release/config/install/core.entity_form_display.node.press_release.default.yml
ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.default.yml
ecms_base/features/custom/ecms_press_release/config/install/core.entity_view_display.node.press_release.teaser.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_agency.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_body.yml
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_press_release_source.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_agency.yml
ecms_base/features/custom/ecms_press_release/ecms_press_release.info.yml

Added new agency select field to the Press Release content type through features 
| Documentation reflects changes? | 
| Did you perform browser testing? | locally
| Did you provide detail in the summary on how and where to test this branch? | There is now an agency multi-select checkbox field on the Press Release content type
| Relevant links | RIGA-514

Add agency select field to the Press Release content type through features

---

.github/workflows/develop.yml
CHANGELOG.md
composer.json
scripts/ci-develop.sh
scripts/develop.sh

Updated Drupal Core to 10.3  and removed/updated patch
| Relevant links | [RIGA-526](https://thinkoomph.jira.com/browse/RIGA-526)

Riga 526/patch update

---

ecms_base/features/custom/ecms_basic_page/config/install/core.entity_form_display.node.basic_page.default.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_form_display.node.emergency_notification.default.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_view_display.node.emergency_notification.default.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/core.entity_view_display.node.emergency_notification.teaser.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_expire_date.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/field.field.node.emergency_notification.field_emergency_weight.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_expire_date.yml
ecms_base/features/custom/ecms_emergency_notification/config/install/field.storage.node.field_emergency_weight.yml
ecms_base/features/custom/ecms_emergency_notification/ecms_emergency_notification.info.yml

This PR adds two fields to the Emergency Notification content type that is part of a feature.
In addition, an item in the basic page feature is changed since the script to remove UUIDs was run on the codebase.
| Relevant links | [RIGA-511](https://thinkoomph.jira.com/browse/RIGA-511)

RIGA 511: Add global notification type V2

---

CHANGELOG.md

- RIGA-548: Update the list of Google translation options.
- RIGA-546: Fixed the icon formatter.
[1.0.7]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.0.6...1.0.7

Prepare changelog for 1.0.7

---

.github/workflows/develop.yml
CHANGELOG.md
ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_json_to_file.yml
ecms_base/modules/custom/ecms_health_file_migration/config/install/migrate_plus.migration.health_file_redirect.yml

Update the config files that describe 
- health_file_json_to_file
- health_file_redirect
Update the source to be the same as the one for
- health_file_json_to_resource_media
That is, set it to https://health.ri.gov/rss/pubs/publications-total-en.json.php
| Relevant links | [RIGA-520](https://thinkoomph.jira.com/browse/RIGA-520)

RIGA-520: Change migration source

---

CHANGELOG.md

- RIGA-549: Add jQuery UI Accordion module
- RIGA-520: Fixed health migration.
- RIGA-520: Update the source file for English Health migration.
- RIGA-549: Update Allowed Formats module
- RIGA-549: Update Automatic Entity Label module
- RIGA-549: Update Automated Logout module
- RIGA-549: Update Components! module
- RIGA-549: Update Entity Print module
- RIGA-549: Update External Links module
- RIGA-549: Update Feeds module
- RIGA-549: Update Layout Builder Restrictions module
- RIGA-549: Update Page Manager module
- RIGA-549: Update the github actions to V3
[1.0.8]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.0.7...1.0.8

Prepare CHANGELOG for 1.0.8 release

---

CHANGELOG.md
ecms_base/modules/custom/ecms_feeds/src/Feeds/Parser/EcmsPressReleaseParser.php

This adds a new feeds parser to handle the agency field by mapping the `<category>` channel field to the `field_agency`.
Create a new feed, select the `RI.gov Agency Syndication` and map the agency fields. Import and confirm the value is set on the items.
| Did you apply meaningful labels to the pull request? |Yes
| Documentation reflects changes? | No
| Unit/Functional tests cover changes? |No
| Did you perform browser testing? |Yes
| Relevant links | [RIGA-558](https://thinkoomph.jira.com/browse/RIGA-558)

Riga 558/feeds fix

---

CHANGELOG.md
ecms_base/modules/custom/ecms_layout/ecms_layout.module

This fixes an issue where adding media within a layout builder block gives a permission error. This is a known bug in Core. See: https://www.drupal.org/project/drupal/issues/3106315
As a site admin, add a new layout page and add a custom block that contains a `media` library widget.
n/a
| Relevant links | [RIGA-524](https://thinkoomph.jira.com/browse/RIGA-524)

Fixed the permission issue with Layout Builder and Media Library

---

CHANGELOG.md
ecms_base/modules/custom/ecms_api_publisher/src/EcmsApiPublisherInstall.php
ecms_base/modules/custom/ecms_api_recipient/src/EcmsApiRecipientInstall.php

Fix an error where there is a missing value when Consumers are created for eCMS API Publishers and Recipients
As a site admin, enable the ecms Publisher module (if it is not already enabled). Go to `/admin/config/services/consumer` and verify that the page loads without error.
| Unit/Functional tests cover changes? | yes
| Relevant links | [RIGA-534](https://thinkoomph.jira.com/browse/RIGA-534)

RIGA 534: Fix Consumer Creation

---

CHANGELOG.md
ecms_base/themes/custom/ecms/ecms.theme

This adds a guard clause to the conditional to prevent a `null` reference when loading the layout builder default layout screen.
Browse to `admin/structure/types/manage/licensee/display/default/layout` and confirm the page loads.
n/a
| Relevant links | [RIGA-531](https://thinkoomph.jira.com/browse/RIGA-531)

Added NodeInterface guard to conditional

---

CHANGELOG.md

- RIGA-588: Added new feeds parser plugin for press releases.
- RIGA-531: Fixed error loading layout builder admin layout page.
- RIGA-534: Fix consumer creation
- RIGA-524: Fixed layout builder issue with media library.
[1.0.9]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.0.8...1.0.9

Prepare CHANGELOG for 1.0.9 release

---

ecms_base/config/install/honeypot.settings.yml
ecms_base/ecms_base.install

Adds new honeypot form settings.
All webform nodes should have honeypot configured with a time limit of 3s.
n/a
| Relevant links | [RIGA-586](https://thinkoomph.jira.com/browse/RIGA-586)

Riga 586/honepot config

---

CHANGELOG.md
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install

This adds the metatag_open_graph submodule as a requirement for installation and an update hook to install it on all existing sites.
| Did you provide detail in the summary on how and where to test this branch? |no
| Relevant links | [RIGA-570](https://thinkoomph.jira.com/browse/RIGA-570)

Riga 570/enable opengraph

---

ecms_base/modules/custom/ecms_languages/ecms_languages.module

This alters the Google Translate library version to ensure caching is cleared. This is necessary because the custom ecms_translator block is extending this library, but doesn't have direct access to alter the libraries.yml.

Update block caching issue

---

ecms_base/modules/custom/ecms_languages/ecms_languages.module

Disable preprocessing for the language js to bypass cache issue.

Disable cache and preprocess from the js

---

CHANGELOG.md
ecms_base/modules/custom/ecms_workflow/ecms_workflow.module
ecms_base/modules/custom/ecms_workflow/ecms_workflow.post_update.php
ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php

This 
1. adds a new method to revoke workflow permissions from roles
2. Revokes emergency notifications from non-drupal_admin roles.
3. Adds post update to remove role permissions from existing sites
4. Adds post update to unpublish all notifications.
- Confirm only `drupal_admin` has permission to create/edit emergency notification content types.
- Confirm all `emergency_notification` content types are archived/unpublished.
| Risk level |medium
| …

Riga 588/update permissions

---

ecms_base/modules/custom/ecms_workflow/src/EcmsWorkflowBundleCreate.php

Extends #558  and revokes the missing `edit own {type} content`.

Revoked missing permissions

---

CHANGELOG.md

- RIGA-570: Added metatag_open_graph to the base install.
- RIGA-576: Added recipe to configure press release publisher module.
- RIGA-576: Added recipe to configure hub site for publishing.
- RIGA-588: Revoked permission for the emergency_notification content.
- RIGA-588: Unpublished all emergency_notification content.
- RIGA-586: Updated honeypot configuration
- RIGA-572: Changed the Google Translate block/styles
- RIGA-576: Hide the press release topics field from display.
[1.1.1]: https://github.com/State-of-Rhode-Island-eCMS/ecms_profile/compare/1.1.0...1.1.1

Prepare changelog for 1.1.1

---

CHANGELOG.md
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install

Uninstall drupal/tour from base install.
[ RIGA-602](https://thinkoomph.jira.com/browse/RIGA-602)

Riga 602/uninstall tour module

---

CHANGELOG.md
composer.json
ecms_base/ecms_base.info.yml
ecms_base/ecms_base.install

Adds the `drupal/mysql57` contributed module and installs it for all sites through an update hook.
Confirm the module is enabled and the site is functioning normally.
n/a
| Unit/Functional tests cover changes? |n/a
| Relevant links | [RIGA-601](https://thinkoomph.jira.com/browse/RIGA-601)

Riga 601/mysql upgrade

---

ecms_base/recipes/ecms_api_press_release_publisher/recipe.yml

Fixes the automated script to remove the role import until Core is upgraded to 10.4.
[RIGA-512](https://thinkoomph.jira.com/browse/RIGA-614)

Commenting out the roles as it breaks the installation

---

CHANGELOG.md

- RIGA-512: Added emergency_notification publisher module.
- RIGA-601: Added the `drupal/mysql57` module as a requirement.
- RIGA-624: Added the `drupal/purge_file` module as a requirement.
- RIGA-605: Press Release Agency field updates
- RIGA-602: Uninstall drupal/tour from base install.
- RIGA-613: Added missing Apple icons and Favicon to the theme.

Prepare changelog for 1.1.3

---

CHANGELOG.md
ecms_base/features/custom/ecms_press_release/config/install/field.field.node.press_release.field_agency.yml
ecms_base/features/custom/ecms_press_release/config/install/field.storage.node.field_agency.yml

- Add Dept of Housing and Other to the Press Release Agency Field.
- Add Help Text under agency field.  -- This field is used for the filter criteria on Ri.gov.
| Did you provide detail in the summary on how and where to test this branch? |no
| Relevant links | [RIGA-627](https://thinkoomph.jira.com/browse/RIGA-627)

RIGA-627/press release content type update

---

CHANGELOG.md
ecms_base/config/install/openid_connect.client.windows_aad.yml

The Azure API Endpoint v1.6 was deprecated, causing the logins to break. This config is overridden on the systems, but I wanted to change it here to ensure it is captured and codified.
See: https://www.drupal.org/project/openid_connect_windows_aad/issues/3518500#comment-16064261
I left the update hook off as it is not required in this instance because of the configuration override.
[RIGA-647](https://thinkoomph.jira.com/browse/RIGA-647)

Updated the Microsoft API endpoint

---

composer.json

Remove patch for Layout Builder Iframe Modal
as [https://www.drupal.org/project/layout_builder_iframe_modal/issues/3344339](https://www.drupal.org/project/layout_builder_iframe_modal/issues/3344339) has been fixed

RIGA-603/Remove patch for Layout Builder Iframe Modal

---

composer.json

This adds a temporary fix to re-hide the `rebuild layout` link after upgrading layout_builder_iframe_modal to 1.3.6. The real issue is with scoping in the Pattern Lab css, but I don't want to update that css during the SDC migration.

Adding temporary fix to hide layout link

---

composer.json

This pull request updates the `composer.json` file to include a new patch reference for Drupal features and modifies the version constraint for the `drupal/features` package. These changes are part of ongoing work to support Drupal 11 upgrades.
* Added a new patch reference for Drupal 11 upgrades under `drupal/features`. This patch supports compatibility improvements for the upcoming Drupal version. (`[composer.jsonR54-R56](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R54-R56)`)
* Changed the version constraint for the `drupal/features` package from `^3.11` to `3.x-dev` to allow for development versions that may include necessary updates for Drupal 11 compatibility. (`[composer.jsonL136-R139](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf5 …

Updated the features module for Drupal 11

---

CHANGELOG.md
composer.json

RIGA-676: Remove drupal/media_revisions_ui
[RIGA-676](https://thinkoomph.jira.com/browse/RIGA-676)

RIGA-676/remove media_revisions_ui

---

composer.json

Adds the book contributed module for Drupal 11 prep.
[RIGA-728](https://thinkoomph.jira.com/browse/RIGA-728)

Add the book contrib module
